### ISSUE TITLE
Worker.py crashes with traceback

### ISSUE THREAD

**Issue by duncanleo** [modrzew/pokeminer#1]
Hi, when running `worker.py`, I am running into the following issue:

```shell
Exception in thread worker-0:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "worker.py", line 464, in work
    main(worker_no, service, api_endpoint, access_token, profile_response)
  File "worker.py", line 509, in main
    lat=lat,
UnboundLocalError: local variable 'lat' referenced before assignment
```

I'm not sure where to start to resolve this. Thanks!

**Comment by modrzew** [comment]
@duncanleo what step limit are you using?

I'm going to refactor the code in the nearest future so that it can automatically cover whole grid without relying on step limit.

**Comment by duncanleo** [comment]
@modrzew I am using a step limit of 1, as I'm testing it out first with a single account. Is it possible that it is the cause of the crash?

**Comment by duncanleo** [comment]
Ah... I upped the step limit to 2 and it does not crash anymore...

**Comment by modrzew** [comment]
I'll try adding constraint for min grid size, and a nice exception.
