### ISSUE TITLE
Show workers not working

### ISSUE THREAD

**Issue by chromer90** [modrzew/pokeminer#102]
In the live map when I hit the show workers button in the bottom left the page becomes unresponsive and then because I am in google chrome it crashes and gives me the aw snap error.

I have everything else working except that. I need to try to see where my workers are because it is not scanning very accurately compared to my main scanner app for smaller locations.

**Comment by amistad18** [comment]
You have to many workers, and it takes a lot of effort for javascript to draw all that circles on your map. I had the same problem, and I updated the code a little to draw circles (show workers scanning areas) only for selected workers, check this out - https://github.com/modrzew/pokeminer/pull/100

**Comment by chromer90** [comment]
I only have 9 workers is that too many?

**Comment by amistad18** [comment]
Not at all, with only 9 workers it should work like a charm, for me it takes over 1 minute freeze to generate and display over 100 workers and their areas.

Are you trying to display workers and circles on mobile device? Did you try on other browser?

**Comment by Aiyubi** [comment]
the number of workers doesnt really matter. Questions is how many points per cycle in total you have. If you have 9 workers with 1000 points per cycle this would be too much for javascript to handle

**Comment by chromer90** [comment]
@Aiyubi That was it. My points per cycle was extremely high now it is about 40 and it worked immediately.

Another question but I might need to make another issue is that the circles are tiny and very far apart. what should I change to either make them closer together or larger circles?

**Comment by Aiyubi** [comment]
@chromer90 there is no way to make the circles larger - its a limit of the game
and to make them be closer together you need to adjust the lat/long gain. This will give you more points again.

What I did: choose a small area, then adjust the lat/long gain, then increase to the big area.

**Comment by chromer90** [comment]
Thanks that seemed to help alot! I will run it all day today and see if it collects data better. Just need to make more workers now lol
