### ISSUE TITLE
Quick add new accounts to config

### ISSUE THREAD

**Issue by chromer90** [modrzew/pokeminer#104]
I was scanning through all the old issues and could not find one about this. I just created about 60 new accounts and need to add them to the config but doing that manually is tedious and instead of me writing a script to do it for me I was wondering if anyone else already had one done for mass adding accounts to the config document or at least formatting them for quick copy and paste of a bunch at once.

**Comment by Primalpat-** [comment]
I made this.  It allows you to paste in the account credentials and spits them out in the format the config.py wants.

https://jsbin.com/ferelew/edit?html,js,output

Format of pasted text:
AccountName:AccountPass
AccountName:AccountPass
AccountName:AccountPass
AccountName:AccountPass

**Comment by chromer90** [comment]
Yes that is exactly what I needed and it worked flawlessly!
