### ISSUE TITLE
Python 3 Compatibility

### ISSUE THREAD

**Issue by ferazambuja** [modrzew/pokeminer#107]
Hey just downloaded the last "dev" build with the python 3 added.
At least for me the only way to run both worker.py and web.py is using:
`python3.5 worker.py`

I'm on mac and have 2.7 and 3.5 installed. Maybe a head-up on the wiki 👍

**Comment by modrzew** [comment]
You can still run it fine with Python 2.7, Python 3 is optional at this point.

But I'm planning on dropping support for Python 2 soon.

**Comment by ferazambuja** [comment]
I get this with 2.7:
`Traceback (most recent call last):
  File "worker.py", line 11, in <module>
    from pgoapi import (
ImportError: No module named pgoapi`

**Comment by GaelicGamer** [comment]
It sounds like it didn't install pgoapi from the `pip install -r requirements.txt` command, can you try to rerun it and post any errors that occur, and if none occur see if you can run it after that.

**Comment by modrzew** [comment]
Make sure that you use proper `pip` when installing. I strongly suggest to use [virtualenv](https://virtualenv.pypa.io/en/stable/) when installing packages. Or one of its flavours, I personally use [virtualenvwrapper](https://virtualenvwrapper.readthedocs.io/) in tandem with [pyenv](https://github.com/yyuu/pyenv).

**Comment by ferazambuja** [comment]
Will try those thanks. Since I'm the only one having this non-issue, here is the report of it for future reference if needed. It just runs fine.
Here is the message from pip (2.7):
```
 Cloning https://github.com/tejado/pgoapi.git (to 0811db23d639039f968a82e06c7aa15a0a5016b6) to ./src/pgoapi
  Could not find a tag or branch '0811db23d639039f968a82e06c7aa15a0a5016b6', assuming commit.
.....
Command "/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c "import setuptools, tokenize;__file__='/Users/username/Downloads/pokeminer-master-3/src/pgoapi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in /Users/username/Downloads/pokeminer-master-3/src/pgoapi/
```
pip3.5:
```
 Cloning https://github.com/tejado/pgoapi.git (to 0811db23d639039f968a82e06c7aa15a0a5016b6) to ./src/pgoapi
  Could not find a tag or branch '0811db23d639039f968a82e06c7aa15a0a5016b6', assuming commit.
```
