### ISSUE TITLE
Pokemon Icon size

### ISSUE THREAD

**Issue by ferazambuja** [modrzew/pokeminer#108]
Hey, I'm trying to use higher res images of the Pokemons. Like the ones used on PokemonGo-Map v2. Is there a way to reduce the size of icons on the HTML templates?

**Comment by GaelicGamer** [comment]
I'm not sure what your asking, do you mean the rendered size? Or the size of the files themselves?

**Comment by ferazambuja** [comment]
Render size or how big they show on my map.

**Comment by GaelicGamer** [comment]
The actual location where it creates the json that is fed to the webpage is lines 133-143 in web.py     

```
markers.append({
            'type': 'pokemon',
            'name': name,
            'key': '{}-{}'.format(pokemon.pokemon_id, pokemon.spawn_id),
            'disappear_time': pokemon.expire_timestamp,
            'icon': 'static/icons/%d.png' % pokemon.pokemon_id,
            'lat': pokemon.lat,
            'lng': pokemon.lon,
            'pokemon_id': pokemon.pokemon_id,
            'infobox': label
        })
```

If you wanted to use a different directory of images you would modify the static/icons/ line, it sounds like you have a different set you want to use.  As for the scaling on the webpage you would need to modify the correct .html files where it is adding the markers, this would be the map.html and as an example and it would be at lines 214-217:

```
                    var marker = addMarker({
                            position: new google.maps.LatLng(item["lat"], item["lng"]),
                            map: map,
                            icon: item["icon"],
                        });
```

Would need to become:

```
                    var icon = {
                        url: item["icon"],
                        scaledSize: new google.maps.Size(150, 150),
                        origin: new google.maps.Point(0,0),
                        anchor: new google.maps.Point(0, 0)
                    };                 
                    var marker = addMarker({
                            position: new google.maps.LatLng(item["lat"], item["lng"]),
                            map: map,
                            icon: icon,
                            size: (240, 240)
                        });
```

Where the (150,150) would be the scale to use for rendering for the marker.  In this example it will make them very large, you will need to play with those values, making sure to restart the server each time until you find the values that make it what you want.

**Comment by ferazambuja** [comment]
thanks 👍

**Comment by GaelicGamer** [comment]
Went ahead and going to add this while I cleanup some of the html
