### ISSUE TITLE
Compress Images for Faster Map Loads

### ISSUE THREAD

**Issue by GaelicGamer** [modrzew/pokeminer#112]
Been doing some testing, and after throwing the images through some PNGGauntlet Compression, I've experienced much better load times of the map when rendering a large number of icons, I've made a pull request #118  with the new compressed images, additionally I made the normal icons just smaller versions of the icons in the larger-icons folder.

If you would prefer the other Icons I can compress them instead, just seemed a little off that they were so drastically different, is there a reason for that?

Edit: Changed the pull request number to the isolated changes.

**Comment by modrzew** [comment]
Moving discussion to #118.
