### ISSUE TITLE
Some workers are staying at 0% constantly

### ISSUE THREAD

**Issue by Shentang** [modrzew/pokeminer#113]
Hello,

I've re-run pokeminer after trying the AHAAAA original map, but it seems that with 400 accounts I get some "dead' accounts that stay constantly at 0%:
 [W258: C1,P0,0%]        [W259: C1,P2,58%]
[W260: C1,P0,13%]       [W261: C1,P0,10%]       [W262: C1,P0,0%]        [W263: C1,P2,13%]
[W264: C1,P0,0%]        [W265: C1,P3,54%]       [W266: C1,P0,0%] 

How can I debug/fix it?

**Comment by subzerofun** [comment]
i know that has nothing to do with your problem, but how do all of you get hundreds of workers? how did you automate the account creation?

**Comment by plague180** [comment]
There are several scripts out there, I personally took https://github.com/jepayne1138/PTCAccount and heavily edited it to do what I wanted

**Comment by inexion** [comment]
This is because they just changed the minimum scan refresh to 10s on the API side, I'm not sure wherein the code to change this

**Comment by GaelicGamer** [comment]
This is handled by line 189 in the worker.py file, I'm going to make this a config option real quick and then add it to my current pull request.

The line currently in case other pulls move it:
`            time.sleep(random.uniform(5, 7))`

**Comment by GaelicGamer** [comment]
This is now part of the config in pull request #111
