### ISSUE TITLE
Get sleeptime between scans from the server

### ISSUE THREAD

**Issue by Aiyubi** [modrzew/pokeminer#115]
In case you did not notice: minimum time between scans is now 10s
This is a setting that you can get from the api

**Comment by GaelicGamer** [comment]
Can you link me the api call and I can implement it, sorry I would look myself but about to go to bed.

**Comment by Aiyubi** [comment]
in download settings request there should be a field get_map_objects_min_refresh_seconds
(did not test myself)

**Comment by modrzew** [comment]
Added `SCAN_DELAY` in 2055388 as a hotfix. Please update your configs.

I'd want to get both scan delay and scan radius from API if possible, but... getting both of them from API will be hard at this point without big refactor. First of all, I'm not sure whether pgoapi exposes the settings while logging in. Second thing, right now points are divided between workers before any of them even logs in.

It'd be easy to just get scan delay and forget about scan radius, but I'd aim at getting both of them and dropping them altogether from config.

**Comment by Sigi-cz** [comment]
maybe you can log in one worker, get the settings, and then after initialisation is done log in all workers.
