### ISSUE TITLE
Workers Button on the Webpage tries to draw circles at all points, often freezing the webpage

### ISSUE THREAD

**Issue by GaelicGamer** [modrzew/pokeminer#116]
Currently the show workers function calls out to get_points_per_worker() which returns all points and then iterates over them to draw circles.  When scanning over a large area, this will cause the webpage to freeze.

**Comment by modrzew** [comment]
That's expected. You usually don't want to show worker circles all the time, only as you're setting up. I'm not sure whether there's any efficient way on displaying thousands of circles at the same time in Google Maps.

**Comment by GaelicGamer** [comment]
Yeah neither am I, looking into it though just in case, might just be the case where a if(points > some reasonable number) would be useful.

**Comment by Sigi-cz** [comment]
maybe only draw the circles at the border of area assigned to the worker.

**Comment by Aiyubi** [comment]
@Sigi-cz one ot the goals is so you can check if you got holes in your grid. And you can not see holes if you just got the border ones

**Comment by modrzew** [comment]
@GaelicGamer I think "some reasonable number" is implicitly 90 with 10s limit (was 180 for 5s limit) :) Basically it's the amount of points each worker needs to go over in order to finish a cycle. If cycle finishes under 15 minutes, then no spawn should be missed. So you want to have less than 90 points per cycle.

**Comment by GaelicGamer** [comment]
I meant in total, the reason it was hanging was I was running an instance of 400 workers at 115 a piece, resulting in a total of 46,000 circles that would have needed to be drawn, so I was thinking a check on the points count and if its greater than some reasonable total, just not draw the circles.

Actually the more I think about this, the more I'd like to make it so you can just show particular workers points at a time, or all of them if it doesn't break the threshold, for checking coverage as @Aiyubi suggests, and it shouldn't be too hard, I'll take a look at doing something along these lines later tonight.

**Comment by modrzew** [comment]
@GaelicGamer did you try the new map powered by Leaflet? I found it to be way, way faster when it comes to drawing circles. It doesn't freeze my browser *that much*.

**Comment by GaelicGamer** [comment]
No I need to pull it down tonight, but from previous experience I suspect that your right and it will have resolved most of this issue.
