### ISSUE TITLE
Some workers getting exceptions?

### ISSUE THREAD

**Issue by gatomiaurex** [modrzew/pokeminer#117]
Well, what the tittle says, it shows "exception" and don't scan the area assigned to them.

![exception](https://cloud.githubusercontent.com/assets/20795984/17356350/31dbfcf0-5914-11e6-9797-6ddd4f80ddcf.png)

![scanpoints](https://cloud.githubusercontent.com/assets/20795984/17356409/9302ee8a-5914-11e6-9942-368b0a6251e6.png)

**Comment by Aiyubi** [comment]
see the other reports - scan delay got changed again tonight to 10s between scans (up from 5s)

**Comment by gatomiaurex** [comment]
That's already accounted for, changed it to 10, 11, still have the problem, already tried different accounts for the workers getting the exceptions and i am still getting the exceptions.

**Comment by yeusimba** [comment]
how many workers are you running? Rumors are saying theres ip softbans running around for mass connections through one ip

**Comment by gatomiaurex** [comment]
Man, I am dumb, seems like I repeated some logins on the config.py, it tried to login with the repeated info and it got a 15 minutes softban.

Thanks for the help, I have 63 workers running ATM.
