### ISSUE TITLE
After half an hour the DB stops updating.

### ISSUE THREAD

**Issue by rollin** [modrzew/pokeminer#12]
After running for 30-40 minutes the data stops to be added to the db while the logs of the worker.py show that the scan is still going as usuall.

What might be the cause? I saw the same issue in the original project, maybe it is also reproducing here?

**Comment by rollin** [comment]
[Here the issue in question](https://github.com/AHAAAAAAA/PokemonGo-Map/issues/625)

> cant find it anymore but i think on another issue the problem was identified as the token expiring after some time so about every 30 mins a new token has to be requested from the server

Is it the problem?

**Comment by DavidSelem** [comment]
I was about to write about this issue! Hope this could get fixed :(

**Comment by rollin** [comment]
I made a bash script and added it to cron to launch every 30 minutes. Two cycles on my setup last around 28 minutes, so it's a decent workaround, but some data could potentially be lost.
```
kill $(ps aux | grep '[p]ython worker' | awk '{print $2}')
python pokeminer/worker.py -st 15
```

**Comment by modrzew** [comment]
Thanks for noticing! I actually noticed it myself and implemented a safety mechanism that *should* restart a worker after 10 cycles. Seems like it's not working correctly.

The script for killing and restarting process is a nice workaround. Though I'll find the root of this issue and fix it :smiley:

**Comment by Samuirai** [comment]
I think the issues are happening on the API calls in `process_step`. If you add some debugging output to the `AttributeError` exception, you will see it start firing and not finding any new pokemon. I don't really know the API well enough to understand if that means the tokens are invalid or something else is happening.

**Comment by modrzew** [comment]
Thanks, I'll debug it.

Nonetheless v0.2 landed a few hours ago and workers should restart more often. I'm also working on more safety features when worker doesn't find new spawns.

**Comment by crckdns** [comment]
Why not simply requesting new tokens after ~25 Minutes? I think this would solve the problem

**Comment by modrzew** [comment]
I just added a simple mechanism to replace workers that don't report anything for 5 minutes (on top of several other changes). Check out whether it improves things for you.
