### ISSUE TITLE
[Suggestion]7 second scan delay instead of 10 seconds

### ISSUE THREAD

**Issue by Pepejson** [modrzew/pokeminer#123]
According to that https://www.reddit.com/r/pokemongodev/comments/4vxseb/psa_7_seconds_scan_delay_is_enough/
you can change it to 7 seconds or maybe for safety 8 seconds. Always 2 seconds faster than before! :P

**Comment by Aiyubi** [comment]
as someone else commented in the redditpost it is not always enough to take 10.

If I take 11 I'm getting the best results myself :(

**Comment by GaelicGamer** [comment]
This is in the config now, you can just modify the config to whatever value you want.

The setting is SCAN_DELAY
