### ISSUE TITLE
[Suggestion] answer to "how many workers will I need?" for the README

### ISSUE THREAD

**Issue by Aiyubi** [modrzew/pokeminer#124]
Posting this here first so someone else can check my math first.

**For rectangular areas that have optimal distances:**
```
numberofworkers = Area_to_check / Area_of_circle * overlap_correction_factor * scan_delay / 15 minutes
with
Area_of_circle = pi * (70m)²
scan_delay = configvalue
overlap_correction_factor = (overlap_area/2+regular_area) / regular_area =  ( pi -2 + pi ) / (pi) = 2 - 2/pi ~ 1.37
```

**How come this correction factor?**
overlap_area (last formular): http://mathworld.wolfram.com/Circle-CircleIntersection.html
devided by 2 because every overlap belongs to 2 circles

Some example calculation:
```
numberofworkers = Area_to_check / (pi*(70m)²) *1.37 * 10s / (15*60s)
Area_to_check = 96 km² (Wroclaw) = 96 * 10^6 m²
```
->96 workers (best some more to account calculation and delays)

So we see: 1 worker per km²

**Comment by theresthatguy** [comment]
This is very helpful. Thank you.

**Comment by Aiyubi** [comment]
And now a try for *hexagonal* (same link as above):
overlap_area = (pi - 3/2*sqrt(3) *2) * 2
overlap_correction_factor ~ 1.17

*Results:*
numer_of_workers = (pi * radius²) /( pi * 70m²) * 1.17 * 10s / (15*60s) = (radius_in_km)² * 2.65

*Example:*
a radius of 5.5km is around 95km² and with the formular above would be ~80 workers
So we now have 80 instead of 95 workers cause of the reduced overlap.

**Comment by Eskof** [comment]
How can I get "Area_to_check " value? Sorry for dumb question

ty

**Comment by Eskof** [comment]
Hello @Aiyubi  and thanks, I'm pretty noob with math. How may I calculate this with 2 coordinate?
Thanks

**Comment by Aiyubi** [comment]
@Eskof your /report tells you how many km² your area has

**Comment by modrzew** [comment]
[Added](https://github.com/modrzew/pokeminer#how-many-workers-do-i-need) in v0.5.0 IIRC. Thanks @Aiyubi!
