### ISSUE TITLE
[BUG] Error with lat/lon gain

### ISSUE THREAD

**Issue by Aiyubi** [modrzew/pokeminer#125]
Case:
lat1 = 12.000
lat2= 12.005
latgain = 0.001

With those settings the algorithm creates points for non existant workers

**Comment by modrzew** [comment]
Are you talking about config's LAT_GAIN/LON_GAIN, or how it's calculated based on SCAN_RADIUS?

**Comment by Aiyubi** [comment]
@modrzew rectangular grid with lat gain set by yourself. If lat2-lat= n *latgain with n being a natural number.

For this case utils.get_points_per_worker() gives an error cause it trys to
points[worker_no].append((lat, lon))
on more worker_no than calculated

**Comment by modrzew** [comment]
Both rectangular grid and lat/lon gain parameters are deprecated since v0.4.2 which introduced hexagonal grid and SCAN_RADIUS.

**Comment by Aiyubi** [comment]
no if you are planning to remove rectangular grid you are right - then this bug is closed
