### ISSUE TITLE
Cannot find command 'git'

### ISSUE THREAD

**Issue by paul30001** [modrzew/pokeminer#127]
I've used the previous versions of the Pokeminer and they worked fine, but with 0.4.0+ when I run 
pip install -r requirements.txt
I get the following error. I have tried to mess around with it for a few hours now, but I don't really know what I'm doing and it doesn't seem to wanna fix itself :) Please let me know what the problem is,
Thanks guys!

`C:\Users\paulf\Desktop\pokeminer-0.4.2>pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Collecting protobuf>=3.0.0a3 (from -r requirements.txt (line 2))
  Using cached protobuf-3.0.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): flask-googlemaps==0.2.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in c:\python27\lib\site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): flask==0.11.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): coveralls==1.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): werkzeug==0.11.10 in c:\python27\lib\site-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): sqlalchemy==1.0.14 in c:\python27\lib\site-packages (from -r requirements.txt (line 10))
Obtaining pgoapi from git+https://github.com/tejado/pgoapi.git@0811db23d639039f968a82e06c7aa15a0a5016b6#egg=pgoapi (from -r requirements.txt (line 11))
  Cloning https://github.com/tejado/pgoapi.git (to 0811db23d639039f968a82e06c7aa15a0a5016b6) to c:\users\paulf\desktop\pokeminer-0.4.2\src\pgoapi
  Error [Error 2] The system cannot find the file specified while executing command git clone -q https://github.com/tejado/pgoapi.git C:\Users\paulf\Desktop\pokeminer-0.4.2\src\pgoapi
Cannot find command 'git'`

**Comment by Aiyubi** [comment]
you have to have git in you windows path

https://git-for-windows.github.io/

**Comment by paul30001** [comment]
Thank you!!! That fixed it! :)
