### ISSUE TITLE
/report Problem

### ISSUE THREAD

**Issue by Duls1** [modrzew/pokeminer#128]
Hey, 
if i try to /report (http://127.0.0.1:8000/report) i get this Error.
Anybody know whats wrong ???

![problem](https://cloud.githubusercontent.com/assets/20823868/17380186/32ddbfbe-59c6-11e6-8827-cb383547cc07.png)

**Comment by Glennvd** [comment]
Are you sure you have 
REPORT_SINCE = datetime(2016, 7, 29)
In your config.py?

**Comment by Nurech** [comment]
Same issue. REPORT_SINCE = (2016, 7, 29) is present.

**Comment by Duls1** [comment]
@Glennvd thx you helped me... now it works.

I didn´t had the "datetime" in that line 
-> REPORT_SINCE = datetime(2016, 7, 29)
and this line was also missing
-> # coding: utf-8 from datetime import datetime

With that config it works now:

 # coding: utf-8from datetime import datetime

DB_ENGINE = 'sqlite:///db.sqlite'
MAP_START = (##.######, #.######)
MAP_END = (##.######, #.######)
GRID = (1, 3)
CYCLES_PER_WORKER = 3
LAT_GAIN = 0.001
LON_GAIN = 0.0015
AREA_NAME = u'test'

ACCOUNTS = [
    ('#####', '#####', 'ptc'),
    ('#####', '#####', 'ptc'),
    ('#####', '#####', 'ptc'),
]   
TRASH_IDS = [13, 16, 19, 21, 41, 96]
STAGE2 = [3, 6, 9, 12, 15, 18]
REPORT_SINCE = datetime(2016, 7, 29)
