### ISSUE TITLE
Pokeminer barely shows anything

### ISSUE THREAD

**Issue by paul30001** [modrzew/pokeminer#129]
What am I doing wrong? I've been playing around with the values and I can't seem to find the best Scan Radius and Number of Cycles per Worker. 

I'm not really sure what cycles mean in this case. What goes on in 1 cycle? Does the worker scan the same area in every cycle? Or is each cycle simply a piece of the area?
Anyway, here's my config. For some reason Web no Pokemon at all. Previous versions showed a lot! It's not because of all the TRASH IDS I have. 
What's wrong with it?
Area is only about 9 sq. miles

`# coding: utf-8
from datetime import datetime

DB_ENGINE = 'sqlite:///db.sqlite'
AREA_NAME = u'walla walla, wa'
MAP_START = (46.080794, -118.392738)
MAP_END = (46.047927, -118.305596)
GRID = (7, 9)
TRASH_IDS = [10, 11, 13, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 27, 29, 30, 32, 33, 37, 41, 42, 46, 47, 48, 49, 50, 51, 52, 53, 56, 57, 58, 77, 84, 96, 97, 98, 99, 104, 105, 111, 112]
STAGE2 = [
    3, 6, 9, 12, 15, 18, 31, 34, 45, 62, 65, 68, 71, 76, 94, 139, 141, 149
]
CYCLES_PER_WORKER = 7
SCAN_DELAY = 10  # seconds
SCAN_RADIUS = 150  # metres
REPORT_SINCE = datetime(2016, 8, 2)`

**Comment by Brideau** [comment]
I'm seeing similar and I don't have any TRASH_IDS on. I'm trying to test the webhook but I can't detect so much as a pidgey in my downtown. I'm wondering if there was another API change?

**Comment by paul30001** [comment]
How often do they do those changes?

**Comment by Eskof** [comment]
Same problem since ~15-20 mins.

**Comment by paul30001** [comment]
Oh-oh, well, I guess we'll be waiting for a fix :) because I'm not very good with code yet.

**Comment by YonderGod** [comment]
PTC servers are having issues right now, but if this was happening before, I think it's because your scan radius should be 70m.

**Comment by pokemonracer** [comment]
Same here, 300 workers - 0 pokemons in 30 minutes.

**Comment by Brideau** [comment]
Likely related: https://www.reddit.com/r/pokemongodev/comments/4w0mtr/getting_0_pokemon_upserted_in_last_few_minutes/

**Comment by real8787** [comment]
API changes from Niantic.

**Comment by Brideau** [comment]
I'm seeing someone in that Reddit thread posting about "MapObjects in API changed". I haven't programmed anything to read the API directly. Anyone know what that refers to?

**Comment by GaelicGamer** [comment]
Yeah, the response package from the API changed and were working on decoding the new format and where what data is what, going to probably be a couple more hours till the python API projects we rely on are updated.

**Comment by Noctem** [comment]
@GaelicGamer I wouldn't expect a fix that quickly, the changes are more difficult than simple response formatting. The requests are being signed or hashed, and that will have to be reverse engineered for 3rd party clients to mimic.

**Comment by GaelicGamer** [comment]
@Noctem I know, I've was doing my part to try to figure out the hashing method last night for over four hours, I was simply hoping that given what we've seen of Niantec so far that they would have done something simple like a auth key change or the like, instead we're all trying to figure out the unknown6 bytes etc.

**Comment by modrzew** [comment]
Fixed (hopefully) in v0.4.3.
