### ISSUE TITLE
can it show with a circle what area each agent is scanned on the browser? please ty

### ISSUE THREAD

**Issue by MonsterMMORPG** [modrzew/pokeminer#13]
so we can see which area each agent is scanned

I feel like many of the cells are being bypassed and not scanned

so if we can see which area are covered by the agents during the scan would be perfect

ty very much

**Comment by modrzew** [comment]
I'll be refactoring code so that each worker visits every centimeter of its work area, so I think that won't be necessary.

Right now you need to manually adjust by using more workers, and/or increased step limit.

**Comment by MonsterMMORPG** [comment]
ty very much

currently definitely missing so many areas

**Comment by modrzew** [comment]
@MonsterMMORPG code with improved points spreading has been in [v0.3](https://github.com/modrzew/pokeminer/releases/tag/v0.3) for a couple of days already. Please check it out.
