### ISSUE TITLE
When I type "python worker.py" I get an Import Error

### ISSUE THREAD

**Issue by Agnalam** [modrzew/pokeminer#130]
When I type "python worker.py" in the command prompt I get the following text

> Traceback (most recent call last):
>   File "worker.py", line 17, in <module>
>     import config
> ImportError: No module named config

Can anyone help me out?

**Comment by metawurx** [comment]
The error tells you it can't find the required config file.
Did you rename config.py.example to config.py ?

**Comment by Agnalam** [comment]
Yes, config.py is named as such and it is a notepad file. However, in the folder its file type is listed as an "EXAMPLE File" even though it opens up with notepad.

**Comment by Aiyubi** [comment]
you should set your OS to always show file endings.

**Comment by metawurx** [comment]
Yeah sounds like you have file extensions hidden.

**Comment by Agnalam** [comment]
You were right. My OS was hiding file extensions. Thank you.
