### ISSUE TITLE
/report error

### ISSUE THREAD

**Issue by Nurech** [modrzew/pokeminer#132]
Can't solve the issue... Please help! Thanks! :)

![capture](https://cloud.githubusercontent.com/assets/20840114/17411917/c88dff4e-5a82-11e6-9c02-b60bd1598291.PNG)

**Comment by modrzew** [comment]
Do you have any sightings in the database at all? If you started collecting data yesterday, then not likely as API has been broken for 2 days now.

**Comment by Nurech** [comment]
That's probably the issue. Cheers!

**Comment by Vashiru** [comment]
Issue still seems to be occurring, even with the bumped api. Sightings table is indeed empty.
