### ISSUE TITLE
New API implementation

### ISSUE THREAD

**Issue by subzerofun** [modrzew/pokeminer#134]
Hey since the new pgoapi (https://github.com/tejado/pgoapi) is out – does worker.py also need an update?

I´ve got the PokemonGoMap project running and receiving valid responses, but pokeminer doesn´t register pokemon encounters.

My setup has ~40 workers, but none of them report anything. I also see no errors in worker.log (successfull logins, all workers running).

**Comment by kravock** [comment]
I'm sure this will get merged in shortly.

**Comment by real8787** [comment]
Yes, we need this fix :)

**Comment by Aiyubi** [comment]
#135 is trying to fix this

**Comment by real8787** [comment]
Any ETA on this?

**Comment by Aiyubi** [comment]
@real8787 you can just get the pullrequest if you wanna try it now

**Comment by real8787** [comment]
Tried it, didnt work :/

**Comment by modrzew** [comment]
Changes pushed to master and released as v0.4.3 - please check it out.
