### ISSUE TITLE
update not working

### ISSUE THREAD

**Issue by paperc07** [modrzew/pokeminer#14]
I updated all the files and now its not showing pokemon or the workers on the map just a blank gmap

**Comment by modrzew** [comment]
I need more information, like output of both worker.py and web.py before I can actually investigate.

**Comment by even-allmighty** [comment]
Hi I have the same problem.
As far as I can tell it seems to be related to ajax calls to /data and /config from the webinterface.
I am running Pokeminer behind a reverse proxy like using an alias : mydomain.com/pokeminer .

Instead of doing the Ajax call to mydomain.com/pokemine/data and mydomain.com/pokemine/config it seems to go to the root (e.g mydomain.com/data ) which is not available.
The previous version worked fine in this setup.

I am not sure if this is the same problem paperc07 has but this was my observation

**Comment by cryzies** [comment]
http://imgur.com/pW5WvuW

This is the error I got on the latest update

**Comment by paperc07** [comment]
![2016-07-23 09_47_33-python worker py -st 8](https://cloud.githubusercontent.com/assets/9095222/17078210/daebd1a6-50ba-11e6-8a6f-c5f1937145dc.png)


I attached the img which would be fine it it worked like that, but when I go to localhost:8000 I still see nothing but the map of my area

**Comment by paperc07** [comment]
When I did what evan-allmighty did I was still getting this 
http://pastebin.com/RA9gF1QT

I also did see this at the bottom in reference to cryzies reply
trash_list = getattr(config, 'TRASH_IDS')
AttributeError: 'module' object has no attribute 'TRASH_IDS'

so let me go and fix that as well

**Comment by cryzies** [comment]
After a bunch of workers started restarting I got this error: https://imgur.com/a/Cy33E

**Comment by paperc07** [comment]
how the hell did you get so many workers? how do I make a script to get more I had to handmake 7

**Comment by cryzies** [comment]
I use autoit to write my scripts, it's interfacei/pixel based so it's only going to work on my personal setup, sorry mate

**Comment by paperc07** [comment]
no worries thats awesome

**Comment by paperc07** [comment]
@cryzies  Hey buddy, so I got 1000+ emails or whatever, now I am having problems with them logging in? Do I have to activate them somehow, it's weird because some will work and most won't. I had to go down to about 20 and I am still running into issues?

**Comment by even-allmighty** [comment]
Hi @modrzew , I know this issue is 10 days old.
But is there anything that speaks against using relative urls?
Because that would work behind a reverse proxy.

**Comment by modrzew** [comment]
Hm, nothing in particular, it was just easier to use `/static/something` instead of `{{ some_flask_helper_for_getting_url('static/something') }}`, for example.

**Comment by even-allmighty** [comment]
To make it work I just set the baseURL in the templates to "window.location.href" which is the whole url.
Then you only have to remove the "/" in front of the appendix for the ajax urls:
$.get(baseURL + "config", function(response){
$.get(baseURL + "data", function(response){

Is there a case where this won't work?

**Comment by modrzew** [comment]
Reports use `/heatmap` endpoint. Other than that I think it should work.
