### ISSUE TITLE
Warning: Data truncated for column 'lon' at row 1 cursor.execute(statement, parameters)

### ISSUE THREAD

**Issue by theresthatguy** [modrzew/pokeminer#145]
I finally decided it was time to use something other than sqlite. I opted for Mariadb since it can be used as a drop-in for MySQL. I am getting this error when starting worker.py

`./worker.sh
/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py:450: Warning: Data truncated for column 'lon' at row 1
  cursor.execute(statement, parameters)`

**Comment by Aiyubi** [comment]
#52 may give you some hints how to set everything up

**Comment by theresthatguy** [comment]
That sure would have been really helpful earlier. The follow has fixed this error for me.

`alter table sightings modify column lat varchar(128);
alter table sightings modify column lon varchar(128);`
