### ISSUE TITLE
Can you add EncounterId field to your sightings table schema ?

### ISSUE THREAD

**Issue by Mandrakia** [modrzew/pokeminer#15]
Right now it's pretty hard to merge data from multiple sources because the unique ID of the encounter isn't stored.
It should be pretty simple to add and would help immensely in making a huge DB of pokemon spawns.

**Comment by modrzew** [comment]
Sure, I'll add it. And now I have to deal with database migrations :stuck_out_tongue:

**Comment by Mandrakia** [comment]
Sucks :(
I'd love to be able to use the data your users generate in my app 
https://www.reddit.com/r/pokemongodev/comments/4u86i5/heatmap_vizualisation_of_pokemon_spawns_paris/

**Comment by modrzew** [comment]
But if you have pokemon ID, lat&lon and spawn ID in your database, those should be enough to detect duplicates. At least it works for me.

**Comment by ferazambuja** [comment]
Is there a way to easy implement this? It's really cool to see the data on heat maps.

**Comment by Mandrakia** [comment]
I just dealt with a Schema migration of my own :(
Now people scanning or importing pokemons data in real time are able to see non expired pokemons in real time on google map :)

So they can launch the scanner at home and move around with their phone hunting !

**Comment by GaelicGamer** [comment]
Just a note on this, while we should definitely still store this, I've seen evidence that the pokemon encounter id is not unique, its extremely rare and if I have time I'll find the reddit post about it, but just something to keep in mind during your migrations.

**Comment by ferazambuja** [comment]
There is little evidence right now and the only way to find out would is if this data is stored.

**Comment by GaelicGamer** [comment]
I currently store it in my private fork which I'm slowly trying to roll into the new public fork I made of this on github, I've got a few examples in there, but here is the reddit post as well just to add credence to what I said earlier: 

https://www.reddit.com/r/pokemongodev/comments/4vazmk/encounter_id_is_not_unique/

**Comment by ferazambuja** [comment]
Do you mind sharing how you implemented? I got stuck with encoding the encounter_ID to base64 or something else. However was just a few lines on db.py I believe.
It's the only reason i'm not using it.

**Comment by GaelicGamer** [comment]
I just have it as a varchar(40) atm as I use a lot of my data with pokelyzer currently and implement most of that schema as well as a few extra tables for stuff I wanted (like history of gym owners, and history of a pokestop being lured)

I intend to hammer it all down to a nice schema at some point as right now I'm pretty sure there are a few indexes I have that are not used.

**Comment by modrzew** [comment]
Added in v0.5.0.
