### ISSUE TITLE
Pokeminer shows way less Pokemon than before! :(

### ISSUE THREAD

**Issue by paul30001** [modrzew/pokeminer#151]
I'm using 110 workers on about 9 sq miles, which is probably overkill, which is exactly why I'm shocked that I'm only seeing a few Pokemon on the map, and chunks of the map are missing, even though all workers seem to be working. 
Here's part of my config, is this good for 9-10 sq miles? If so, why are only few Pokemon showing up, I don't even have very many TRASH_IDS set up :(
`MAP_START = (46.080794, -118.392738)
MAP_END = (46.047927, -118.305596)
CYCLES_PER_WORKER = 7
SCAN_DELAY = 10  # seconds
SCAN_RADIUS = 70  # metres
REPORT_SINCE = datetime(2016, 7, 31)`

**Comment by Innenseide** [comment]
I didn't test it myself, but I've seen reports on reddit that there seems to be a limit of 60 (or 50?) accounts per IP. Surpassing it could supposedly lead to empty results and/or bans.

Again, just second hand information, but you may want to try reducing your number of workers. I'm *comfortably* covering 23 sq km with 35 workers, which happens to be around 8.5 sq miles or so. What are you trying to do with 110 anyways?

**Comment by PieterxJan** [comment]
Is there maybe some way to visualize what the workers have scanned and how long ago this happend? It would be a bit easier to finetune the amount of workers.

**Comment by paul30001** [comment]
Unfortunately, there's no way to visualize only what they have already scanned - but only the whole area to be scanned.

Innenseide, I will try that and report back.

**Comment by Innenseide** [comment]
@PieterxJan I don't know of such a visualization, but the worker overview in your terminal will tell you how many points your workers have to visit per cycle, and by multiplying that number with your `SCAN_DELAY` you'll find out how many seconds each worker is expected to take for a full scan of its area. In theory, anything up to 900 seconds should be fine to catch each spawn (because most Pokemon are around for 15 minutes), but you should probably include some buffer time. I'm at about 8 to 9 minutes per cycle and everything's looking great.

**Comment by Aiyubi** [comment]
The way scanning works is that it goes through each workers area slowly.

Did you already check your lat(lon gain? On your map bottom left you can see the workers area

if you check your report you see how big your area is in km² -> 1 worker per km² should be fine. Maybe a little more workers.

**Comment by PieterxJan** [comment]
@Aiyubi @Innenseide Thanks for the response. I figured it out how I could debug this the best and I ran the worker.py next to the web.py. In that way, everytime I've changed the config.py file with some other values, I could see the changes in the web-display. 

I'm now scanning ~26.25 points per cycle. But will the workers automatically reset and start over again until I stop the worker.py? 

Thanks in advance!

**Comment by Aiyubi** [comment]
@PieterxJan yes they will restart with some break between scans
Also I recommend a lower value for CYCLES_PER_WORKER

**Comment by PieterxJan** [comment]
@Aiyubi I already have CYCLES_PER_WORKER set on 1. Why would you want to have a lower value there? I can't seem to understand what it does :|

**Comment by Aiyubi** [comment]
@PieterxJan CYCLES_PER_WORKER = how many times should a worker scan its area before it restarts. Its login lasts only a while so restarting is needed to refresh the login.

**Comment by PieterxJan** [comment]
@Aiyubi Thanks for the clarification 👍

**Comment by paul30001** [comment]
@Aiyubi Thank you!
In that case what is the Scan Radius for? What exactly is the radius OF? A worker's whole area or is it only the radius of one of the small hexagons that appear on the map when you "show workers?"

Why is every cycle so much faster in the cmd window when Scan Radius values are high, and it's so much slower when the value is low. It seems counter intuitive.

**Comment by Aiyubi** [comment]
@paul30001 it is how big the small circles(hexagons) are and it is a server setting. If you edit the range to be anything other then 70 it will not work right cause the space between scan gets calculated wrong.
