### ISSUE TITLE
How can I view all of the Pokemon in the Database?

### ISSUE THREAD

**Issue by paul30001** [modrzew/pokeminer#152]
I would appreciate if someone could tell me how I can view ALL previous spawns in the DB for ALL Pokemon, not just the active ones. 
I realize that the map would probably not be readable, but I want to give it a shot. 
Also, is there a way to just show all previous spawns of a certain Pokemon from the DB, instead of ALL of them?

I believe this was the original purpose of the Pokeminer, rather than live monitoring.
I just don't know how to work with databases.

modrzew said "There are two reports:

Overall report, available at /report
Single species report, available at /report/<pokemon_id>"

How do I run and visualize those??

I really need your help, guys! :)

**Comment by Innenseide** [comment]
> modrzew said "There are two reports:
> 
> Overall report, available at /report
> Single species report, available at /report/"
> 
> How do I run and visualize those??

I'm not sure I understand your question... you just have to access those reports in your browser. If the live map is at 127.0.0.1:5000, the report is at 127.0.0.1:5000/report

**Comment by paul30001** [comment]
omg, I love you! no homo haha
That's what I needed, now I can see the report!!!
Thank you!

**Comment by paul30001** [comment]
> the report is at 127.0.0.1:5000/report<

What about the report for single species??
"Single species report, available at /report/<pokemon_id>"
I tried typing in stuff like 
127.0.0.1:5000/report/<16>
and other things like that, but it doesn't seem to work.
What's the proper way to write that address?

**Comment by paul30001** [comment]
What about the report for single species??
"Single species report, available at /report/'<'pokemon_id'>'"
I tried typing in stuff like 
127.0.0.1:5000/report/<16>
and other things like that, but it doesn't seem to work.
What's the proper way to write that address?

**Comment by Aiyubi** [comment]
127.0.0.1:5000/report/16

**Comment by paul30001** [comment]
@Aiyubi Thank you!
Last question:
Is it possible to view the spawn time on the hour of a certain Pokemon? 
I know I can run a report for a single Pokemon, but if there have been, let's say 5 Charizards in my town overnight, I want to know the exact minute of the hour when they spawn and also how many hours are between spawns, if there's any correlation.

Point is, how can I view the actual spawn TIMES?

**Comment by Innenseide** [comment]
> I want to know the exact minute of the hour when they spawn and also how many hours are between spawns, if there's any correlation.

I don't think there's a correlation. I think we know that most spawns have a given minute every hour when they spawn a Pokemon for 15 minutes. They seem to have a set table of possible Pokemon which might be influenced by its surroundings (water etc.), and sometimes a special, rare Pokemon will appear.

**Comment by amistad18** [comment]
@paul30001 Take a look at this - https://github.com/Cy4n1d3/PokeminerSpawns
