### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by photex12** [modrzew/pokeminer#153]
I get the following error when trying so setup this project:

  Error [Error 2] The system cannot find the file specified while executing command git clone -q https://github.com/keyphact/pgoapi.git "C:\Users\Iton\Desktop\New folder (2)\src\pgoapi"
Cannot find command 'git'

**Comment by nhumber** [comment]
you need to install git for windows first, probably python also.
could also need to setup PATH attributes in windows if you still cant find the specified command after install git

those were all the hurdles i faced running python stuff on windows for the first time.

**Comment by photex12** [comment]
OMG haha thank you.
Unfortunately this end up in the following error:

Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\iton\\appdata\\local\\temp\\pip-build-ibqyay\\sqlalchemy\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\iton\appdata\local\temp\pip-ypxvmt-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\iton\appdata\local\temp\pip-build-ibqyay\sqlalchemy\

**Comment by photex12** [comment]
I hardly dare asking but.....encrypt.dll.......I have been searching for 2 hours and I can nog seem te find it :(:( would someone please help me :$

**Comment by nhumber** [comment]
found it?

**Comment by jyh947** [comment]
I'm on the same boat as photex12.  Any help?

**Comment by photex12** [comment]
Yes I found it! Thanks.
