### ISSUE TITLE
Gyms - Fort Branch

### ISSUE THREAD

**Issue by nhumber** [modrzew/pokeminer#154]
First off i know this isn't the right place, But i must say that this has made the playing experience incredible for 100's of players in my home town, I've been using your maps since release, sometimes i follow along with your WIP and move around from your release branch to dev stuff depending on how i feel at the time. 

Getting up and going again yesterday was a great feeling so Thank You, from all of us for all the work you've done!!

Issue: Gyms dont seem to keep current up to date information, im still seeing the same gym information from yesterday when i know the location has been scanned within the last 2 minutes and can see the changes in prestige amounts in person at the location. Im still seeing also seeing a gym in my town thats showing as "empty" when it was only empty for 1 minute yesterday around noon. (assume same issue)

**Comment by modrzew** [comment]
When did you update the branch? There was indeed an issue with showing the oldest entry in the database instead of the newest, but it should have been fixed in 1947484a1802536cc7e28379ef45c6946c4e696a.

Also thanks for the warm words :smiley:

**Comment by nhumber** [comment]
I just made sure the above fix was added and still i see only old gym information.
anything i can do to check the DB?

**Comment by modrzew** [comment]
`forts` was just merged to master and released as v0.5.0. Moreover, I confirmed on my phone that data on map is displayed correctly - all gyms were properly colored, had proper Pokemon and exact amount of prestige.

**Comment by nhumber** [comment]
Version 0.5.0 is working as it should, again: Thank you for your hard work.

**Comment by nhumber** [comment]
seems i've spoke too soon, gyms seemed to stay updated when i did a fresh install of 0.5.0, fast forward to today and im getting no gym updates again.
i saw another issue pertaining to this today, ill do some reading in the comments see if i can get it working

**Comment by modrzew** [comment]
If I understand you correctly, gyms are not updating on the live map, is that correct? But if you refresh the whole map it's OK for some time, right?
