### ISSUE TITLE
Percentages are empty in gym.py

### ISSUE THREAD

**Issue by Kieken72** [modrzew/pokeminer#159]
`percentages[team.value] = (count.get(team.value) / len(forts)) * 100`
is returning 0
`print percentages #{0: 0, 1: 0, 2: 0, 3: 0}`

**Comment by modrzew** [comment]
Are you using Python 2.7?

**Comment by Aiyubi** [comment]
@modrzew got the same - you are deviding int by int in the calculation - python 2.7 gives int as result (0) which you multiply by 100
