### ISSUE TITLE
Please also save in the database PokeStop locations and the GYM locations

### ISSUE THREAD

**Issue by MonsterMMORPG** [modrzew/pokeminer#16]
Thank you very much awesome project

**Comment by matiasmoya** [comment]
I'm very interested in this feature as well! Is goin to add more value to the db :)

**Comment by esolitos** [comment]
That's easy to archive, just look up [Ingress portals](https://www.ingress.com/intel), those are the same. :)

**Comment by modrzew** [comment]
Gym locations are stored as of v0.5.0.
