### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Aiyubi** [modrzew/pokeminer#161]
trying to open /report

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aiyub/PoGo/pokeminer/web.py", line 198, in report_main
    google_maps_key=config.GOOGLE_MAPS_KEY,
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aiyub/PoGo/pokeminer/templates/report.html", line 128, in top-level template code
    <a href="/report/{{ icon[0] }}"><img src="../static/larger-icons/{{ icon[0] }}.png" title="#{{ icon[0] }} {{ icon[1] }}"></a>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 7: ordinal not in range(128)
```

**Comment by khag7** [comment]
Same issue here.

**Comment by Innenseide** [comment]
+1 - I had the relevant commit in my fork before, same thing happened. Couldn't find a solution in my limited time.

**Comment by subzerofun** [comment]
hey i have a fix: 
1) make sure flask is up to date: `$ pip install --upgrade flask`
2) install unidecode: `$ pip install unidecode`
3) open web.py
between `# -*- coding: utf-8 -*-` and `from datetime import datetime`
paste this:
```
import sys
reload(sys)
sys.setdefaultencoding("utf-8")
from unidecode import unidecode

```
4) save and try to run 
`python web.py --host 127.0.0.1 --port 8000` (or whatever localhost/port is)
again

5) please tell me if it works - this is my first time trying to help someone on github :-)

**Comment by Innenseide** [comment]
@subzerofun this fixed it for me. Awesome!

**Comment by khag7** [comment]
another way to fix is to edit pokeminer/templates/report.html and remove the title attribute from any img tag (there are 4 total).

**Comment by subzerofun** [comment]
ok this might be an easier solution. i however will nonetheless now open a bottle of the finest wine from my cellar and celebrate the day when for the first time i actually helped someone on github instead of just bulk downloading the hard work of other people. 

Santé my short sighted friends, Santé! i will dedicate this glass to the greatest company in the world - AVIATO! :bowtie: :wine_glass:

**Comment by subzerofun** [comment]
pardon me, the greatest company in the world is of course [http://www.bachmanity.com/]

**Comment by Aiyubi** [comment]
okay got some debugging done - seems to be the pokemon names. Guess it's Nidoran. Will debug more.

**Comment by Aiyubi** [comment]
okay did some more investigation: if I rename 29 to Nidoran(w) and 32 to Nidoran(m) it works fine. (for english)

**Comment by khag7** [comment]
i feel silly for not thinking of that. i was looking in the template for non ascii characters and couldnt figure it out. DUH its the m and f symbols. good catch!

**Comment by plague180** [comment]
yep, subzerofun's solution worked for me

**Comment by modrzew** [comment]
By the way, this problem (as well as whole unicode hell) is nonexistent in Python 3 - I tested @Noctem's fix using py3 and it worked for me (that's why I didn't catch it). If you haven't upgraded yet, now is the time!

**Comment by modrzew** [comment]
It should be fixed as of c3fd59dc64f94 (in master) for those who *still* use Python 2.7. I seriously advise to upgrade to Python 3, pokeminer works flawlessly on it.

**Comment by Innenseide** [comment]
@modrzew You should probably post that advice to the README. Most projects around Pokemon Go seem to be designed for Python 2.7 and wherever I looked, one of the favorite FAQ items was "use 2.7!" Personally, I've been so used to that, I just went with 2.7 for Pokeminer without thinking about it.

**Comment by modrzew** [comment]
@Innenseide good idea, thanks!

**Comment by Noctem** [comment]
Hmm, I thought I had tested with Python 2 without issues (which surprised me). But I completely second @modrzew's endorsement of Python 3.
