### ISSUE TITLE
for migration to 0.5, is there a sql for the new tables for import into mysql?

### ISSUE THREAD

**Issue by vDrag0n** [modrzew/pokeminer#165]
I've looked at the sql, and it seems it only changes the sightings table.  Is there one for the new tables forts and forts sightings?

**Comment by Aiyubi** [comment]
check out the 0.5.0 release notes: https://github.com/modrzew/pokeminer/releases/tag/v0.5.0

**Comment by vDrag0n** [comment]
This works for mysql too?

**Comment by Aiyubi** [comment]
Did this for mysql, so yes

**Comment by freakjam** [comment]
@vDrag0n try this little guide https://github.com/modrzew/pokeminer/issues/52#issuecomment-235907854
