### ISSUE TITLE
ctypes _dlopen error

### ISSUE THREAD

**Issue by josepotud** [modrzew/pokeminer#170]
I've updated the pokeminer with the new api and I'm getting this error and I can't find a solution. Any idea?

`[2016-08-08 01:42:09,625][  worker-0][    INFO][L 285] Adding 'DOWNLOAD_SETTINGS' to RPC request including arguments`
`[2016-08-08 01:42:09,640][  worker-0][   ERROR][L 119] A wild exception appeared!`
`Traceback (most recent call last):`
`  File "worker.py", line 101, in run`
`   password=config.ACCOUNTS[self.worker_no][1],`
`  File "c:\users\josel\pogo\pokeminer-master\src\pgoapi\pgoapi\pgoapi.py", line 164, in login`
`    response = self.app_simulation_login()`
`  File "c:\users\josel\pogo\pokeminer-master\src\pgoapi\pgoapi\pgoapi.py", line 141, in app_simulation_login`
`    response = request.call()`
`  File "c:\users\josel\pogo\pokeminer-master\src\pgoapi\pgoapi\pgoapi.py", line 210, in call`
`    request.activate_signature(lib_path)`
`  File "c:\users\josel\pogo\pokeminer-master\src\pgoapi\pgoapi\rpc_api.py", line 85, in activate_signature`
`    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)`
`  File "C:\Users\josel\Anaconda2\lib\ctypes\__init__.py", line 440, in LoadLibrary`
`    return self._dlltype(name)`
`  File "C:\Users\josel\Anaconda2\lib\ctypes\__init__.py", line 362, in __init__`
`    self._handle = _dlopen(self._name, mode)`
`WindowsError: [Error 126] No se puede encontrar el módulo especificado`

**Comment by skiniemini** [comment]
Check hints at [#135](https://github.com/modrzew/pokeminer/pull/135)
