### ISSUE TITLE
MySQL issue with recent update

### ISSUE THREAD

**Issue by kravock** [modrzew/pokeminer#172]
Keep getting the following error with the most recent update. I am using MySQL for the database, and have created the new tables and run the migration

https://gist.github.com/kravock/6e91e6d3e35d94f2d9e41b4252b9a204

**Comment by kravock** [comment]
Fixed in PR #175

**Comment by Aiyubi** [comment]
could it be that gyms.py now adds all different sightings of gyms together?

**Comment by NCDKorrigan** [comment]
SQL statement needs to be changed or ONLY_FULL_GROUP_BY (on your mysql server) disabled: http://stackoverflow.com/questions/23921117/disable-only-full-group-by

**Comment by modrzew** [comment]
Moving discussion to #175.
