### ISSUE TITLE
Is google maps key no longer needed?

### ISSUE THREAD

**Issue by YonderGod** [modrzew/pokeminer#173]
> switched to Leaflet for live map engine

so we no longer need
`GOOGLE_MAPS_KEY = 's3cr3t'`
in config, right?

**Comment by kravock** [comment]
Nah, doesn't use Google Maps anymore.

**Comment by grenadesonfire** [comment]
I think the heatmaps are still using google maps. I get an error when I try to run them and when I pop open the web dev console I get this 'Google Maps API error: InvalidKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key-map-error '

**Comment by DavidSelem** [comment]
Google maps is used by the report feature

**Comment by YonderGod** [comment]
Ohhh, I see.

**Comment by modrzew** [comment]
Reports will be moved to Leaflet too. It has a few plugins for heatmaps, too.
