### ISSUE TITLE
Can't view the /report! 

### ISSUE THREAD

**Issue by paul30001** [modrzew/pokeminer#182]
Running the 0.5.0 version, and I can see the active Pokemon on the map, but cannot run the report! :(
Here's what I get, How do I fix it? It's saying something about the Google Maps Key, but I though we're using LeafLet now, right?
![11](https://cloud.githubusercontent.com/assets/20823132/17514239/55ee504e-5de6-11e6-840b-739cf003b486.png)

**Comment by paul30001** [comment]
Now it won't even show the live Pokemon on the map :( but let's address the 1st issue 1st, please haha

**Comment by Aiyubi** [comment]
just read the last line - you do not have a google api key set. Check your config

**Comment by paul30001** [comment]
@Aiyubi, added the API to the config, not I'm getting this when trying to run a report 
![screensho11t](https://cloud.githubusercontent.com/assets/20823132/17514876/f9eee4bc-5de9-11e6-8705-2cf7677cabba.png)

**Comment by Aiyubi** [comment]
you should really start looking on other issues which have the same error message #161

**Comment by paul30001** [comment]
@Aiyubi  Sorry :), that helped, BUT I still can't view live Pokemon for some reason though, the LeafLet map loads but doesn't have any Pokemon on it,
I was showing some in the beginning, but not anymore :(
What could be the problem?

**Comment by Innenseide** [comment]
@paul30001 I'd bet there's some error message on the terminal that is running web.py. Look there, **think about it**, look through previous issues, try to fix it yourself, and if all that won't yield any success (it should), then ask further questions. Please.

**Comment by modrzew** [comment]
The unicode error should be fixed as of c3fd59dc64f94 (in master).
