### ISSUE TITLE
[report] UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 7: ordinal not in range(128)

### ISSUE THREAD

**Issue by hitagisenjogahara** [modrzew/pokeminer#187]
When trying to generate /report have that message. Never appeared before .5 release. So far I managed to sort out all issues but this one has something to do with unicode and I have no clue how to bite it.

**Comment by skiniemini** [comment]
Already been duplicate issues [dup #182](https://github.com/modrzew/pokeminer/issues/182) [orig #161](https://github.com/modrzew/pokeminer/issues/161)

**Comment by hitagisenjogahara** [comment]
Cheers, been checking for similar issue but might be the time of the day to late. Sry for hassle.

**Comment by modrzew** [comment]
Fix for that is already in master, I'll release new version Soon™.
