### ISSUE TITLE
Nightmare installing pip for Python 3

### ISSUE THREAD

**Issue by paul30001** [modrzew/pokeminer#189]
Someone please be a good Samaritan here :0

So I saw @modrzew comment on one of the issues here saying that Pokeminer runs much smoother on Python 3.
So 1st: Which Python? 3.0.0? 3.0.1? or like 50 other releases after 3?
I've uninstalled 2.7, and tried installing 3.0.0 AND 3.0.1 and followed gprez's guide on the installation.
https://pip.pypa.io/en/stable/installing/ says that I simply need to upgrade pip, since it comes with Python 3.
Regardless, I've tried upgrading AND installing it from scratch multiple times. 

With Python 2.7 I just BSed my way through it until it worked.
When I try to run get-pip.py the cmd flashes, but I was able to record it and take a still.
It randomly shows the 2 different errors in the pictures.

Someone please let me know how to actually install pip in the case, because pip website just gives command prompt commands without explaining where or how to run them, or what to do when they don't work. 
Also, when I run "python -m pip install -U pip" in Python directory, it says "no module named pip" 

![screenshot_2016-08-09-15-04-29](https://cloud.githubusercontent.com/assets/20823132/17535692/fb9ec8b2-5e44-11e6-835a-963cb5b3a13e.png)
![screenshot_2016-08-09-15-03-48](https://cloud.githubusercontent.com/assets/20823132/17535693/fd356f96-5e44-11e6-91cc-d7a489d25e1d.png)

**Comment by pokemonracer** [comment]
First of all. Extract all those files from the zip-file to a folder. Then open cmd in that folder (shift + right click, "Open command window here") where you extracted the files and type python get-pip.py. 

You can use the latest Python 3 version. 

Protip: take screenshots, no need for pics taken by phone.

**Comment by paul30001** [comment]
I have done that many times. I'm not sure what you mean by zip: python zip or pokeminer zip?
But just in case, I did both, here you go, Python 3.0.0 and pokeminer, here are the errors, same thing :( 
![screenshot 30](https://cloud.githubusercontent.com/assets/20823132/17538247/9366152a-5e58-11e6-88fe-607f1eb09146.png)
![screenshot 29](https://cloud.githubusercontent.com/assets/20823132/17538248/936640ae-5e58-11e6-94d2-02f79efe2348.png)

**Comment by paul30001** [comment]
Okay, I actually managed to install the latest python version properly and update pip to 3.1.2 or something like that, now when I run the pip install -r requirements.txt in the pokeminer folder it gives me this! Something wrong with permissions! What do I do?
![screenshot 31](https://cloud.githubusercontent.com/assets/20823132/17538777/58af1404-5e5d-11e6-80b8-f1432524f68f.png)

**Comment by paul30001** [comment]
Installed last version of python and pip, and here's what I get when installing requirements for pokeminer.
Please someone explain :'( 
I'm so confused, could this have something to do with admin rights? I made myself admin already! 
![screenshot 32](https://cloud.githubusercontent.com/assets/20823132/17539019/759cba2e-5e5f-11e6-828d-5c70aebf50f2.png)

**Comment by Aiyubi** [comment]
you do not like googling?
http://www.pandastack.com/unable-to-find-vcvarsall-bat-how-to-fix-on-windows/

**Comment by paul30001** [comment]
@Aiyubi Sorry haha
I did Google it, found similar issues, and yeah I installed the C++ Compiler 14 already, there were a couple more errors, but I figured it out.

I'm just really new to Python, that's why I keep creating new issues here. 
Anyway, hard work and BSing my way through it payed off! haha
I just don't know how the Pokeminer runs smoother on Python 3 than on 2.7, maybe all this was for nothing haha

**Comment by modrzew** [comment]
I didn't say it runs *smoother*. I said that Python 2.7 has not been supported (i.e. developed) for 6 years already, and all new things I want to use in pokeminer are in Python 3. They may not matter that much to the end user, but they matter so, so much to the developer.

Moreover, you should stick to the most recent version of Python 3 - right now it's 3.5. I've been running it for long time already without bigger issues.
