### ISSUE TITLE
normalized_timestamp = 1468878720

### ISSUE THREAD

**Issue by Sigi-cz** [modrzew/pokeminer#19]
while looking through results, I noticed a lot of DB entries with incorrect timestamps. 240 from 2500 to be exact. The DB was created today, but all of those 240 normalized_timestamp are equal to 1468878720.

**Comment by modrzew** [comment]
Normalized timestamps work in that way. I used them previously to find duplicated spawnings and don't insert them twice to database. The field you're probably interested in is `expire_timestamp`.

**Comment by Sigi-cz** [comment]
the `expire_timestamp` are also incorrect 1468878814.922 and so on.

**Comment by Sigi-cz** [comment]
I created new DB and during first minute got 6 from 48 of those entries. Using latest master without modifications.

**Comment by modrzew** [comment]
Could you share your database, or tell me what should I look for?

**Comment by Sigi-cz** [comment]
https://drive.google.com/open?id=0B-Ooacf9MSABRGVpckJkSHRsWDg
normalized_timestamp = 1468878720
expire_timestamp is also weird for those entries

**Comment by modrzew** [comment]
Yeah, I now see it... definitely strange. But that's the data coming from the server - I don't know why would the endpoint return pokemons with negative TimeTillHiddenMs. I'll look into it.

**Comment by modrzew** [comment]
Fix just landed in [v0.3](https://github.com/modrzew/pokeminer/releases/tag/v0.3) - Pokemon with negative TimeTillHiddenMs shouldn't be added to database anymore.

**Comment by Sigi-cz** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1879

**Comment by modrzew** [comment]
That date (July 18 at 21:38 UTC) is consistent with your timestamps and sightings I gathered. Although it doesn't seem to me like those are "some kind of special spawn", I'd rather say it's a bug on Niantic side. Unless someone confirms that such spawn shows in the app and is catchable - then I'll be convinced.

**Comment by Sigi-cz** [comment]
The spawns are there, I forgot to liknk this one: https://github.com/AHAAAAAAA/PokemonGo-Map/issues/509
It seems like PokemonGo-Map switched to something else than pokemon.proto with 2.0 release?

**Comment by modrzew** [comment]
Alright, I'll look into that. Thanks!

**Comment by Sigi-cz** [comment]
https://www.reddit.com/r/pokemongodev/comments/4ui7um/pokemon_go_mapscan_optimized_code/d5qxkny

**Comment by Sigi-cz** [comment]
Ok I got it. Those negative times are for 30min spawns opposite to regular 15min spawns.
the relation between the time values is ExpirationTimeMs = LastModifiedMs + TimeTillHiddenMs
with negative TimeTillHiddenMs the formula is ExpirationTimeMs = LastModifiedMs + TimeTillHiddenMs + 841345181
this will give correct despawn time

**Comment by Sigi-cz** [comment]
Nah, the "constant" is different for each 30/45 min spawn.
But they should be displayed on the map, even with negative TimeTillHiddenMs.

**Comment by Sigi-cz** [comment]
https://www.reddit.com/r/pokemongodev/comments/4v71xp/60_minute_long_spawn/
