### ISSUE TITLE
Index error, and Pokemon not showing.

### ISSUE THREAD

**Issue by paul30001** [modrzew/pokeminer#191]
So after hours of messing around I managed to get the new Pokeminer running properly with the latest Python, I saw some Pokemon on the live map a few hours ago, but then it stopped showing anything.

Workers seems to be fine, but the map is empty and when trying to run the report, I get this. And I JUST got the new API for the config.
Help pls! haha 
![error](https://cloud.githubusercontent.com/assets/20823132/17541995/b0eefaaa-5e79-11e6-8359-bc83936a4b6c.png)

**Comment by modrzew** [comment]
The same as #137. Do you have encryption library? Did you check the logs? (`worker.log`)

**Comment by paul30001** [comment]
@modrzew Yes, I have the encryption library, with Python 2.7 I was using a "encrypt64bit.dll" library, but for some reason the latest Python release installed a 32-bit version, so I got the appropriate library, and it was all working at first, then just suddenly stopped. 

Anyways, I just got home, and it's working again. Maybe some issues with all the Google logins...

I have 3 questions for you though: 
-How often do I need to get a new API key?
-I have 49 workers at 70 points per cycle  with 5 sec SCAN_DELAY, means it should take them ~350 sec per cycle, right?? Well, it actually seems to be more than an hour in reality, plus some are on like P15 when others are still on P2, why is that?
-Do you have any plans of implementing a notification system (for ex. Pushbullet)? 
It would be SUCH AN AMAZING addition - receiving notifications of Charizards spawning in any part of town haha

**Comment by paul30001** [comment]
@modrzew SCRATCH ALL THAT
So it just happened to me again - the map stopped showing things, and report doesn't change. 
The workers were running for about 10 minutes, and then I see all of them saying "KILLED", and after they restarted, they act like they're scanning but nothing new shows on the map! I've noticed this before.

And the /report shows the same amount of Pokemon as it did before they all said KILLED.
So obviously they're not getting any new sightings even though they are scanning.
I, of course, restarted them a few times now, but it didn't help.

Why does it do that? And what does KILLED mean?

**Comment by Aiyubi** [comment]
@paul30001 have you checked the accounts ingame? If yes: can you show us your config without the accounts part (as this is private information)

They get KILLED when they did not find anything for 10 minutes

**Comment by Aiyubi** [comment]
oh just read the last post: set your scan delay to a minimum of 10 seconds....

**Comment by paul30001** [comment]
@Aiyubi Here: I cropped the API, in case you were wondering why I don't have it! I set the scan delay to 10, and still no luck! 
It seems like they keep getting "KILLED" as soon as they reach 100% on P0 (first point) - screenshots attached (sorry for the dim brightness)

![screenshot 36](https://cloud.githubusercontent.com/assets/20823132/17549423/f6645262-5ea4-11e6-936c-bfb0c7f3617c.png)
![screenshot 33](https://cloud.githubusercontent.com/assets/20823132/17549422/f661a29c-5ea4-11e6-8a60-0372be01ba62.png)
![screenshot 37](https://cloud.githubusercontent.com/assets/20823132/17549424/f66777b2-5ea4-11e6-8e02-f2587510f4d8.png)


. 
I don't know why this is.
And why are some, so much further ahead than the others? Percentage-wise.

**Comment by paul30001** [comment]
HEELLLPPP :( 
sorry for spamming

**Comment by Aiyubi** [comment]
your config looks fine but P0 means no pokemon found

you did not answer if you logged into those accounts? did they accept the TOS?

**Comment by gunawanputra** [comment]
@paul30001 could you give more information about your worker.log?
for workers,  maybe you could try the PTC account creator app, so you can use many workers as possible

**Comment by paul30001** [comment]
@Aiyubi I did mention that I didn't check them (log into them), but regardless they were working fine, and I just woke up, and a few minutes ago all 49 of them were finding Pokemon, but now I got the same issue :( 
Anyway, I'm using the tool to create PTC accounts instead right now as @gunawanputra said. I'll keep you guys posted.

**Comment by paul30001** [comment]
@modrzew @Aiyubi @gunawanputra 
So I created a bunch of PTC accounts, the creator app verified them and I even logged in to a few to make sure, and yeah, they were already verified. 
But I got the same problem - P0 - no Pokemon.
When I start the worker.py, most or all of the workers say EXCEPTION at first and then start scanning, is that normal?

Also, is it ok to just double click worker.py and web.py, or is it better to start them from command line? 
Anyway, I have tried both, and they don't work.
It seems like it starts working for a few minutes when I don't scan for a few hours and then it stops working again. 
:'(

**Comment by paul30001** [comment]
@modrzew @Aiyubi 
Here's my worker.log after running it for about 20 seconds, second half of it is quite interesting. 
This time all but 1 said EXCEPTION, but even when none of them say that, it still doesn't find Pokemon.
I would REALLY appreciate if you guys took a look at the log. 
Something about "slow down man"
http://www.filedropper.com/worker
LINK IS SAFE

**Comment by paul30001** [comment]
Could it be that Niantic banned my computer ip or something like that?

**Comment by gunawanputra** [comment]
Yup there's something about ip ban, I just experience the same problem with you. I restart my connection and the it working again

**Comment by paul30001** [comment]
@gunawanputra What do you mean by restart your connection? 

How do I set dynamic IP? I'm using a router.

**Comment by gunawanputra** [comment]
I'm using 4g modem and only got shared ip, so what I did was cut my connection and connect again to get a new ip. If your ip is dedicated you could try this tips http://www.hackingdistrict.com/threads/pokemon-go-quick-ip-unban.247/

**Comment by paul30001** [comment]
So it's definitely my IP.
I have a dynamic IP, and I tried everything to change it from changing my router's MAC, to cloning it, to releasing the IP and renewing it, even tried unscrewing the COAX cable from my modem for a few minutes, nothing worked...
EXCEPT I think I just extremely lucky and my Dynamic IP JUST changed! So the Miner is working again. 
But if anyone has this problem try the things I just listed. They may help change the IP.

**Comment by gunawanputra** [comment]
the reason you get no pokemon is because when the ip is got banned, there is no token or ticket get from google or ptc when we send request. That will make our request to niantic server invalid and only recieve cell id and current timestamp from the server. 

If worker reach 100% without get any pokemon it will get kill and restart. Each worker percentage could be different because when worker restart on any reason the progress will reset to 0% and worker will scan from starting point, also when a cell is full of fort and pokemon, worker will take more time to insert all  the data to db, before move to the next point.

**Comment by paul30001** [comment]
@gunawanputra Yeah, I realize that it got banned, read my last post.
But thank you! Your 2nd paragraph actually explains a lot!

**Comment by paul30001** [comment]
Also, I figured out that the Index Error happened because I had 0 Pokemon in the database! I
