### ISSUE TITLE
Workers not running (pokelyzer, base64)

### ISSUE THREAD

**Issue by BallTongue0** [modrzew/pokeminer#194]
I'm on OS X 10.11.6 and running python 3.5.
I got the Pokelyzer worker.py and config.py files and i get this error when starting the workers.

[2016-08-10 11:00:30,478][  worker-0][    INFO][L 225] Point processed, 0 Pokemons and 4 forts seen!
[2016-08-10 11:00:30,503][  worker-1][    INFO][L 260] Cleanup of request!
[2016-08-10 11:00:30,506][  worker-1][   ERROR][L 141] A wild exception appeared!
Traceback (most recent call last):
  File "worker.py", line 136, in run
    self.main()
  File "worker.py", line 198, in main
    'encounter_id': b64encode(str(pokemon['encounter_id'])),
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/base64.py", line 59, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
TypeError: a bytes-like object is required, not 'str'

I believe it's something with the decoding of the encounter_id but I'm not that great with code... Someone with more knowledge might be able to help me?

**Comment by modrzew** [comment]
So Python 3 handles strings in better way than Python 2, which may be confusing in the beginning - but only in the beginning!

b64encode accepts type called `bytes`, which is - as name indicates - a sequence of bytes. `pokemon['encounter_id']` is an Unicode string. Those two are not compatible without conversion. So before putting it in the database you need to convert `str` to `bytes`. And afterwards you'll probably be left with `bytes` object returned by `b64encode`, which you'll need to convert to string again.

http://stackoverflow.com/questions/8908287/base64-encoding-in-python-3#8909233

**Comment by BallTongue0** [comment]
Thanks @modrzew!
I think i got it, but is there anything i could do?

**Comment by modrzew** [comment]
Modify your code :stuck_out_tongue_winking_eye:

Open up Python 3 REPL (by running `python`) and experiment for a bit. Import b64encode, run `b64encode('test!')` and rework it until it actually does what you need.

**Comment by Aiyubi** [comment]
@BallTongue0 or ask @Brideau since he developed that specific part:
https://www.reddit.com/r/pokemongodev/comments/4wtbsq/pokeminer_integration_with_pokelyzer_betaish/

**Comment by BallTongue0** [comment]
I will try getting it to work with python 2.7 instead. @Brideau said he didn't know how to get it to work in 3.5!

**Comment by modrzew** [comment]
@BallTongue0 alright, here's the snippet:

```py
from base64 import b64encode

b64encode('test!'.encode('ascii')).decode('utf-8')
```

Why would you b64encode the encounter_id anyway?
