### ISSUE TITLE
Issues with triggering pokemon layer

### ISSUE THREAD

**Issue by kravock** [modrzew/pokeminer#196]
If you trigger the pokemon layer off and on after having the page open for a while, once the pokemon layer is reactivated all the pokemon that have despawned show in the map again. See link for example http://puu.sh/qwjdO/cbfacf04bb.jpg

**Comment by modrzew** [comment]
Yeah, I noticed that too.

**Comment by gunawanputra** [comment]
typo on Pokemon overlay. on variable desc it's Pokemon but on line 129 (newmap.html) it's Pokemons.
