### ISSUE TITLE
Where are the config files ?

### ISSUE THREAD

**Issue by DeastinY** [modrzew/pokeminer#2]
No submodule, no config.py

**Comment by modrzew** [comment]
Right now you need to create `config.py` by yourself - an example is in the readme.

I'll think of better guide for newcomers, in the meantime you may check [this wonderful guide](https://www.reddit.com/r/pokemongodev/comments/4tz66s/pokeminer_your_individual_pokemon_locations/d5lovb6) on Reddit.

**Comment by DeastinY** [comment]
this guide is so great.
why is it not in the readme :D?

**Comment by modrzew** [comment]
Because I was too lazy and focused on making it work in the first place :smiley: I'll be cleaning the code soon, and I'll think about a guide then.

**Comment by DeastinY** [comment]
Well, let me handle it then :)
I should have a little downtime this weekend, you can focus on more important heatmaps then ;)
