### ISSUE TITLE
RESTART sometimes causes exception

### ISSUE THREAD

**Issue by cryzies** [modrzew/pokeminer#20]
https://i.imgur.com/yMZYpmu.jpg

**Comment by cryzies** [comment]
Temp fix by wrapping the erroring line with a try/except

**Comment by cryzies** [comment]
Temp fix lead to new error: https://imgur.com/a/c7tpZ

**Comment by modrzew** [comment]
Every time I'm looking at your screenshots I'm astonished by the number of your workers :smiley:

I'll look into that.

**Comment by Bifros7** [comment]
I'm facing the same issue.

**Comment by Eduardox** [comment]
Some of my workers get stuck at 1-5%, will they eventualy keep moving?

**Comment by modrzew** [comment]
I just merged code to master that checks upon workers every 5 minutes and replaces those that are stuck for some reason (either at 0%, or running around and not seeing a single spawn). Please check it out - I'm closing the issue, but feel free to open new one in case there's anything wrong.
