### ISSUE TITLE
[Suggestion] Worker.py - Change local IP used

### ISSUE THREAD

**Issue by skiniemini** [modrzew/pokeminer#201]
It would be great to be able to specify the IP to use when starting the `worker.py`.
Example: `python worker.py --host 127.0.0.1`

Mainly so you can use different public IP addresses, depending on which local IP you use. I'm currently running multiple instances on multiple machines but having each machine route out using a different public IP address. This allows me to run a lot of workers without the servers choking me down on the amount of accounts that are logged in.

Thoughts? Is this already possible?

**Comment by DavidSelem** [comment]
web.py -H 127.0.0.1 -P 5121

**Comment by skiniemini** [comment]
@DavidSelem I know you can specify the port and host IP for the web server. I want to be able to specify the IP that the worker.py communicates out on when communicating with Niantic's servers

**Comment by YonderGod** [comment]
I don't understand what you're asking. Your internet connection has 1 ip. If you have multiple internet connections, they will each have their own ip already.

**Comment by skiniemini** [comment]
@YonderGod I have a block of static IP addresses for my one internet connection. I can assign certain devices one of the IP's from the block.

**Comment by YonderGod** [comment]
hmmm, what do I know? 

Is it a business internet service or something?

**Comment by Arxk** [comment]
You have to change the settings of your device manually or use a proxy/VPN. There is no way to do what you are asking for.

**Comment by paul30001** [comment]
Lucky you, I have one dynamic IP for my router, so ALL devices have the same IP until it changes or until I unscrew the COAX cable haha

**Comment by modrzew** [comment]
It's not possible to the extend of my knowledge. Making requests (i.e. being a client) is different than serving content (i.e. being a server).

But you can try using proxy, support for that was added and should work.

**Comment by paul30001** [comment]
@skiniemini Maybe write a quick Visual Basic app to launch an IP Blocker or a Proxy Auto Changing Program every time you start worker.py.
