### ISSUE TITLE
How do I setup proxy?

### ISSUE THREAD

**Issue by paul30001** [modrzew/pokeminer#204]
I do not know where to start.
How do I add proxy? What's the easiest way? 
I would prefer a high anonymity IP, since my last IP got flagged, so I had to wait till it changed dynamically.
Step by step pls? :)

**Comment by phr34k0** [comment]
YES! How?

**Comment by paul30001** [comment]
Where do I find good proxy IP addresses? I've tried many free websites for them, the workers keep saying EXCEPTION!

**Comment by phr34k0** [comment]
@paul30001 _It_ IS free

**Comment by paul30001** [comment]
So I just paste any IP address and ports from those Proxy database websites?

**Comment by phr34k0** [comment]
@paul30001 tor and privoxy. Google that up

**Comment by Baklap4** [comment]
Maybe it's a good thing to create a tutorial for windows/mac/linux on the wiki?

**Comment by paul30001** [comment]
Yeah, especially for a Proxy that can't be seen as Proxy. I don't mind paying a few bucks per month if that means the Pokeminer will run smoothly on a good Private Proxy
