### ISSUE TITLE
Problem with worker.py?

### ISSUE THREAD

**Issue by slxdegrees** [modrzew/pokeminer#206]
I'm getting this message whenever I try to run worker.py

> Traceback (most recent call last):
>   File "worker.py", line 383, in <module>
>     spawn_workers(workers, status_bar=args.status_bar)
>   File "worker.py", line 317, in spawn_workers
>     start_worker(worker_no, points[worker_no])
>   File "worker.py", line 305, in start_worker
>     points=points
>   File "worker.py", line 82, in __init__
>     center = self.points[0]
> IndexError: list index out of range

**Comment by Aiyubi** [comment]
this indicates a worker has 0 points - can you check your config?
and in case you dont find anything please copy paste your map_start, map_end and grid variables here

**Comment by slxdegrees** [comment]
It turned out the problem was with my grid. Tweaked it and it seems to be working as it should now. Thanks!
