### ISSUE TITLE
GPS tracking

### ISSUE THREAD

**Issue by nebbyz** [modrzew/pokeminer#21]
Is there a way to have this track my location on the map when using my mobile browser?

**Comment by paperc07** [comment]
I was wondering this? also how can we make it to where it covers the whole city and not just a line across?

**Comment by modrzew** [comment]
There definitely is, and it's quite easy to implement - but live map is low on my priorities list, as pokeminer is mainly data gathering tool.

**Comment by modrzew** [comment]
I added simple GPS tracking (or rather map-centering) in f99f577c458be586d21c1a19ea5070052051a1cb, and will put it together with v0.4 soon.
