### ISSUE TITLE
Over 35690min left on timer

### ISSUE THREAD

**Issue by BallTongue0** [modrzew/pokeminer#219]
I don't know what happened but i restarted my workers and started the web.py and about 20% of all pokemons have a really long time left to despawn, i don't mind if it's a graphical bug but I'm worried that it will mess up the database...

**Comment by BallTongue0** [comment]
I reinstalled poke miner and it solved the issue.

**Comment by paul30001** [comment]
You mean just delete the folder, and unpack again?
