### ISSUE TITLE
What's this all about? 644 hours

### ISSUE THREAD

**Issue by paul30001** [modrzew/pokeminer#220]
I've been running the Pokeminer for 2 days, but this morning the report tells me it's been running for 644 hrs and that it's September right now. 
Also, #219 !!
Same here, but now it's 36661 minutes, looks like it's all counting down to that End Date of the report in the screenshot? 
Are you predicting the end of the world, @modrzew ?

![screenshot](https://cloud.githubusercontent.com/assets/20823132/17636375/97d3016e-6091-11e6-8755-64791575883c.png)

**Comment by BallTongue0** [comment]
I reinstalled it all, lost 3 days of data mining but it works again... But i will be following this thread to see what caused the problem... I think for me i messed up the files myself...

**Comment by paul30001** [comment]
Why didn't you save the db.sqlite file? Could've pasted it in the new installation and kept all your data.

And what do you mean my reinstall?

**Comment by paul30001** [comment]
I'll just use 1.5.2 for now until 1.6.0 final comes out

**Comment by gatomiaurex** [comment]
Suddenly pokemons on the map show this despawn timer

35603m 

Is this the same error? Is there a way to fix it?

**Comment by Aiyubi** [comment]
nia changed something about the server responses.
Protos discussion about this: https://github.com/AeonLucid/POGOProtos/pull/184

**Comment by gatomiaurex** [comment]
I read the link you gave me but I can't find the file they are modifying to make the changes. ;_ ;

**Comment by paul30001** [comment]
Will modifying it fix the problem?

**Comment by gatomiaurex** [comment]
I don't know, i was just asking ._. 

The only way I was able to fix it is to delete the database and running it again. :(

**Comment by batttie** [comment]
//EDIT: location .\pogom\pgoapi\protos\POGOProtos_src\Map\Pokemon\WildPokemon.proto

**Comment by gatomiaurex** [comment]
Thanks, that seems to fix it, is there a way to delete all the pokemons that are stuck in the map with the broken despawn time?

**Comment by seikur0** [comment]
That protos change doesn't really fix it. Get this:
https://github.com/modrzew/pokeminer/pull/222

**Comment by YonderGod** [comment]
To delete all the pokemon that are stuck on the map, I deleted the last 25k (probably overkill) rows in my database. 
Idk if there's a better way to do it.

**Comment by gatomiaurex** [comment]
wouldn't a SQL query to delete anything with a despawn timer above 15 minutes be better? I don't know how to do it, tho

**Comment by paul30001** [comment]
Is there a way to open db.sqlite where it's readable?? That way we could Find and Delete the bad entries.

**Comment by paul30001** [comment]
I'm working on filtering them out, give me a few mins.

**Comment by paul30001** [comment]
Guys, I'm so proud of myself, I've actually figured something out haha
This is to filter out all the long expiry Pokemon after you have fixed the reason that makes them appear.

Steps:
-http://sqlitebrowser.org/ - get your version
-OPEN a copy of db.sqlite
-Browse Data Tab
-Select Sightings in drop down list on top
-For expire timestamp, put 1473173782.527
-Ctrl+A, and Delete all those entries.
-File -> Write Changes.
-Copy and Paste that same db file into Pokeminer.

*Make sure you don't work with the original one, so if you mess up, you can redo it. Make a reserve copy.
Ta-da!

**Comment by TristanHM** [comment]
Thanks Seikur and Paul. All looks well after applying pull request 222 as a patch and deleting the rows from the database based on the expire timestamp.

**Comment by paul30001** [comment]
@TristanHM How do you apply it as a patch? I just manually edited the file

**Comment by TristanHM** [comment]
@paul30001 Fair warning, I'm a novice when it comes to this sort of thing. You can download the pull request as a patch by adding '.patch' to the end of the pull path i.e. 'https://github.com/modrzew/pokeminer/pull/222.patch'. Then apply it on the command link by git apply <Path to Patch>.

**Comment by paul30001** [comment]
Thank you! Even after your explanation it'll take me a while to figure it out.
I'm very new to GitHub and Python

**Comment by Innenseide** [comment]
The following sql query should catch and remove all invalid entries:
`delete from sightings where encounter_id in (select * from sightings where expire_timestamp > 1473000000)`

Other than that, we should probably aim to handle those timestamps another way than simply dropping them, like the lines following https://github.com/favll/pogom/issues/266 show for pogom?

**Comment by rollator** [comment]
> 
> 
> The following sql query should catch and remove all invalid entries:
> delete from sightings where encounter_id in (select encounter_id from sightings where expire_timestamp > 1473000000)
> 

instead of `delete from sightings where encounter_id in (select encounter_id from sightings where expire_timestamp > 1473000000` you could also just use `delete from sightings where expire_timestamp > 1473000000
`
no need for the select statement :)

**Comment by Baklap4** [comment]
I'm with Innenside. Dropping those lines is not the way to go. Especially for a data mining program as this one should not consider dropping entries.

**Comment by Aiyubi** [comment]
@Baklap4 once they are below 15 minutes and you scan them they will be added. No problem deleting them since they are doubled in your database.

**Comment by rollator** [comment]
@Baklap4 actually he's dropping them too, the queries have the same effect except mine runs faster ;)

as for dropping them, would you propose a different solution so that the db only contains valid data?

**Comment by seikur0** [comment]
@Aiyubi: That's not true for 1x60 spawns, that spawn every hour one pokemon for one hour, they never have a real tth and won't ever be added.

**Comment by Kobito123** [comment]
@paul30001  I dont have any entries with  1473173782.527 :/ sry i am kinda new to this.

**Comment by nhumber** [comment]
look for the entry with something close, 99 percent of my DB was 1471xxxxxx you need to remove all the 1473xxxxxx entries. 

then i made these changes here and i've been good to go since, https://github.com/favll/pogom/pull/266/files

**Comment by modrzew** [comment]
Meh. Sorry for delay. Fixed in 568fb3ef71b17c79a5d08d56a16dea77b525ac14 by @seikur0 (#222), fix is already in master and in freshly released v0.5.3.
