### ISSUE TITLE
db.get_forts(session) is returning ALL fort rows, not just the most recently modified row for that fort

### ISSUE THREAD

**Issue by snicker** [modrzew/pokeminer#224]
This is making my `/data` calls 13-15mb, and refresh is unbelievably slow

**Comment by snicker** [comment]
Seems to be because the query is grouping by the primary key and the fort_id. Should only be by fort ID. for my region, this is the difference between ~350 rows and ~80,000 rows. All being dumped to JSON and sprayed out to the client.

**Comment by snicker** [comment]
Disregard this, I apparently did not update when I thought I did,looks to have been fixed already!

**Comment by Aiyubi** [comment]
in case you notice something strange. I fixed it returning old data for me #198
