### ISSUE TITLE
Killed Workers

### ISSUE THREAD

**Issue by DavidSelem** [modrzew/pokeminer#236]
I just pulled the newest commits and now my workers are getting killed after a few minutes, this shows up in the log

`[2016-08-15 14:43:11,847][ worker-78][   ERROR][L 145] A wild exception appeared!
Traceback (most recent call last):
  File "worker.py", line 139, in run
    self.main()
  File "worker.py", line 179, in main
    cell_id=cell_ids
  File "C:\Users\David\Desktop\pokeminer - copia\pgoapi\pgoapi.py", line 131, in function
    return request.call()
  File "C:\Users\David\Desktop\pokeminer - copia\pgoapi\pgoapi.py", line 232, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "C:\Users\David\Desktop\pokeminer - copia\pgoapi\rpc_api.py", line 140, in request
    raise ServerSideRequestThrottlingException("Request throttled by server... slow down man")
pgoapi.exceptions.ServerSideRequestThrottlingException: Request throttled by server... slow down man`

**Comment by Aiyubi** [comment]
what is your SCAN_DELAY ?

**Comment by DavidSelem** [comment]
12 seconds

It was working just fine, until I update it

**Comment by DavidSelem** [comment]
Downloaded 0.5.3 and now it's working flawlessly

**Comment by Svsk** [comment]
There is something related to [this commit](https://github.com/modrzew/pokeminer/commit/53d80dd302d89cb7229420eab4c0fe7037a8db36) that's causing workers not to be restarted. I don't believe it's to do with the exception above though. On the first worker check I get some workers killed and they're never restarted. I reverted the changes of that commit and it started working again. I haven't been able to narrow it down further.

**Comment by modrzew** [comment]
Sorry. I just merged #237, this should fix the issue with logger.
