### ISSUE TITLE
Spawns seen per 5 minute steadily decreasing

### ISSUE THREAD

**Issue by Jugg1e5** [modrzew/pokeminer#256]
I started a scan a few days ago and was averaging around 220 mons/5 mins.  Then, after a day or so this dropped to around 200, then later 180, then 150, 130, and now around 90.  I'm running 40 workers in an area of about 33 sq.km., and none of them seem to have any problems (no exceptions/kills/bad-logins).  I do notice that some of them will go an entire cycle and not see a single pokemon.  Is this a type of ban for those accounts?  I've attached a graphic to show what I mean.  The drops to 0 are travel times with no internet, usually to and from work.
![example](https://cloud.githubusercontent.com/assets/20750533/17811423/00746564-6623-11e6-9ae5-b4f27a3fbfa1.png)

**Comment by FFroehlich** [comment]
I am pretty sure that your accounts are getting banned.

**Comment by amistad18** [comment]
All workers are working? If you restart, and start again, chart is going up again?

**Comment by gunawanputra** [comment]
Look for "Point processed, 0 Pokemons and 0 forts seen!" in your log file, if you have a lot this message, that could be an indication that your acounts soft-banned

**Comment by Jugg1e5** [comment]
Yea, probably some sort of ban.  I'm just surprised I'm still able to successfully log into all of these accounts.  I would have expected more exceptions/errors.  Thanks.
