### ISSUE TITLE
Notification sent to Facebook Message

### ISSUE THREAD

**Issue by weizh888** [modrzew/pokeminer#263]
I am using a remote computer to do the scanning, and it is hard to access/control the computer using a cell phone. It would be great to receive the information (spawn, time left, and location/direction) through FB message. I know there is a branch about using Twitter, but still have some trouble to set it up. Can anyone help? Thanks in advance.

**Comment by and7ey** [comment]
Facebook? You can easily do it with Telegram.

**Comment by weizh888** [comment]
@and7ey Would you mind to tell how to realize that? Thanks
