### ISSUE TITLE
How to change the leaflet map to another

### ISSUE THREAD

**Issue by tcrouch199205** [modrzew/pokeminer#264]
As the title suggests, I'm looking at changing the default leaflet map to a hybrid map. In the config, we are provided with "MAP_PROVIDER_URL" and "MAP_PROVIDER_ATTRIBUTION", however the hybrid map has more to it than just those two. The one I'm interested in switching to is [HERE.HybridDay](https://leaflet-extras.github.io/leaflet-providers/preview/#filter=HERE.hybridDay), and I can not seem to figure it out.

**Comment by leclaida** [comment]
for it to function you only need to change the url. i've never used here, but after scanning their documents it looks easy enough. copy and paste the url from that link you sent (the one with {x}, {y}, {z}). fill in app id and all the other things by registering with HERE.

go here:
https://github.com/leaflet-extras/leaflet-providers

then scroll to providers requiring registration.

**Comment by tcrouch199205** [comment]
I've gotten the url set up with the proper app id and app code. When running the scanner the map doesn't load images, and instead it shows a grid filled with unloaded image icons.

**Comment by leclaida** [comment]
can you paste here what you are putting into your config file?

**Comment by tcrouch199205** [comment]
I'm using 

> MAP_PROVIDER_URL = 'https://1.aerial.maps.cit.api.here.com/maptile/2.1/maptile/newest/hybrid.day/13/4400/2686/256/png8?app_id={YOUR_APP_ID}&app_code={YOUR_APP_CODE}'

I've also replaced the {YOUR_APP_ID} and {YOUR_APP_CODE} with the appropriate information.

**Comment by leclaida** [comment]
try:

MAP_PROVIDER_URL= '//{s}.aerial.maps.cit.api.here.com/maptile/2.1/maptile/newest/hybrid.day/{z}/{x}/{y}/256/png8?app_id={app_id}&app_code={app_code}&lg=eng

fill in your app id and app code.

**Comment by tcrouch199205** [comment]
Trying what you provided still leads the a map filled with unloaded image icons. I'm starting to wonder if it's on HERE's side and not on anything that I might be doing.

**Comment by leclaida** [comment]
so i made my own app id and app code so i could see what was happening. turns out the url isnt being passed correctly because of the &

i'm not familiar with how to escape the & in python, but you can still use your map if you open up newmap.html (using notepad++ or something similar). scroll to the bottom and you should see:
L.tilelayer(' {{MAP_PROVIDER ' )

replace that so that you have:

L.tilelayer('//1.aerial.maps.cit.api.here.com/maptile/2.1/maptile/newest/hybrid.day/{z}/{x}/{y}/256/png8?app_id={app_id}&app_code={app_code}', [OTHER STUFF])

**Comment by Aiyubi** [comment]
let me guess: you guys are using python2.7 ? You could also try to set the string to unicode like:
MAP_PROVIDER_URL= u'your_url'
(note the u, did not test this)

**Comment by tcrouch199205** [comment]
Alright, I've gotten it to work by replacing that bit of code in the newmap.html. Thanks for all your help!
