### ISSUE TITLE
Access the map from your phone through IP?

### ISSUE THREAD

**Issue by gatomiaurex** [modrzew/pokeminer#268]
I was using PokemonGo-Map and accessing the map through http://publicip:5000, I started using pokeminer again and it seems it's no longer possible, is this intended? I can access it using Ngrok but it stops working from time to time due to too many connections and localtunnel spends more time crashing than working.

Thanks in advance.

**Comment by Aiyubi** [comment]
still working fine for me - did you check the output of web.py for errors?

**Comment by leclaida** [comment]
also make sure you are not just hosting it on localhost. not sure if pokemongo-map defaults to 0.0.0.0 or not.

otherwise it would be a portforwarding issue.

**Comment by gatomiaurex** [comment]
Seems like adding the -H 0.0.0.0 thing when running web.py solves this problem, thanks for your help.
