### ISSUE TITLE
web.py only shows pokemon in a line

### ISSUE THREAD

**Issue by kazyka** [modrzew/pokeminer#27]
As the title state, when I run the web.py and browse to localhost:8000 the pokemons are only shown in a straightline, not in the entire grid. 

Did I set this wrong up or is there an error?

**Comment by Bifros7** [comment]
What does your GRID line in config.py say?

**Comment by afrogunso** [comment]
I have the same issue, my GRID line in config.py is: GRID = (8,8)

Here is a screenshot to illustrate the issue:

![pokeminer_line](https://cloud.githubusercontent.com/assets/20631159/17087491/3913d570-51a7-11e6-81e9-88d52b18db47.PNG)

**Comment by modrzew** [comment]
That's expected shortly after running. Each worker has a good amount of points to scan (status bar should tell you how many), and it takes a couple of seconds for each point (depending on server load). Check out after each worker finishes its cycle, there should be more Pokemon on the map.

**Comment by modrzew** [comment]
I'll double check whether algorithm for distributing points on map doesn't have any bugs, and whether worker actually visits all of them. Maybe order of visiting needs change.

**Comment by kazyka** [comment]
@Bifros7 It says (3, 4)

@modrzew I kept it running for 2-3ish hours, but the pokemons stop showing after 1 hour. But the pokemons just dissapered from the map. The workers just get from left to right.

**Comment by toddstpad** [comment]
I still have this issue in 3.1 along with #44.  Not really sure why I'm only scanning in a straight line OR some workers error out on #44 and don't scan at all.  I went from 42 workers to 2 x 20 workers that seems to alleviate some of issue #44, but they still only really scan from a LEFT to RIGHT line from a NorthWest point of the worker point and scanns RIGHT of this imaginary line as shown in the above screenshot

**Comment by modrzew** [comment]
Sorry for lack of update, I have dev branch with grid algorithm slightly revamped to start from worker's position (and also made sure that worker visits all of the points) AAAAAAAAAAND I decided this is the perfect time to refactor `worker.py` so that it uses pgoapi library, on the same branch. ETA? Tomorrow, maybe on Thursday.

**Comment by modrzew** [comment]
Of course, by "Thursday" I obviously meant Saturday.

Anyway a few changes just landed in master, and worker should go in circles around its starting point - please check it out.
