### ISSUE TITLE
Wild exception - Cannot find module

### ISSUE THREAD

**Issue by Foxbond** [modrzew/pokeminer#270]
As title says

- windows
- pokeminer master/9d5cfe8 (0.5.4)
- python 2.7.12 (pokeminer 0.6 needs 3.5)
- pip 8.1.2

Log:
`[2016-08-23 20:59:09,638][  worker-4][    INFO][L 103] PTC User Login successful.`
`[2016-08-23 20:59:09,638][  worker-4][    INFO][L 121] Request PTC Access Token...`
`[2016-08-23 20:59:09,867][  worker-4][    INFO][L 149] PTC Access Token successfully retrieved.`
`[2016-08-23 20:59:09,868][  worker-4][    INFO][L 144] Starting RPC login sequence (app simulation)`
`[2016-08-23 20:59:09,868][  worker-4][    INFO][L 295] Creating a new request...`
`[2016-08-23 20:59:09,868][  worker-4][    INFO][L 304] Adding 'GET_PLAYER' to RPC request`
`[2016-08-23 20:59:09,868][  worker-4][    INFO][L 304] Adding 'GET_HATCHED_EGGS' to RPC request`
`[2016-08-23 20:59:09,868][  worker-4][    INFO][L 304] Adding 'GET_INVENTORY' to RPC request`
`[2016-08-23 20:59:09,868][  worker-4][    INFO][L 304] Adding 'CHECK_AWARDED_BADGES' to RPC request`
`[2016-08-23 20:59:09,869][  worker-4][    INFO][L 300] Adding 'DOWNLOAD_SETTINGS' to RPC request including arguments`
`[2016-08-23 20:59:09,871][  worker-4][   ERROR][L 132] A wild exception appeared!`
`Traceback (most recent call last):`
`  File "worker.py", line 106, in run`
`    provider=service,`
`  File "D:\Python27\lib\site-packages\pgoapi\pgoapi.py", line 178, in login`
`    response = self.app_simulation_login()`
`  File "D:\Python27\lib\site-packages\pgoapi\pgoapi.py", line 155, in app_simulation_login`
`    response = request.call()`
`  File "D:\Python27\lib\site-packages\pgoapi\pgoapi.py", line 225, in call`
`    request.activate_signature(lib_path)`
`  File "D:\Python27\lib\site-packages\pgoapi\rpc_api.py", line 81, in activate_signature`
`    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)`
`  File "D:\Python27\lib\ctypes\__init__.py", line 440, in LoadLibrary`
`    return self._dlltype(name)`
`  File "D:\Python27\lib\ctypes\__init__.py", line 362, in __init__`
`    self._handle = _dlopen(self._name, mode)`
`WindowsError: [Error 126] Nie można odnaleźć określonego modułu`

**Comment by leclaida** [comment]
do you have the encrypt.dll in the root folder of pokeminer?

**Comment by Foxbond** [comment]
@leclaida No, how I can acquire it?

it's not mentioned in readme or tutorial

**Comment by Aiyubi** [comment]
just search for [Error 126] in the issues - you will find the answer

**Comment by leclaida** [comment]
check the pokemon go map reborn github repository, look for the libencrypt folder. you will want either encryptx32.dll or encryptx64.dll depending on your computer (you already said windows). download then put into the root of the pokeminer folder (i.e. alongside worker.py, config.py, db.py, etc.). go into config.py and change the encrypt_path to what it should be for your new encrypt file. (i.e. if you downloaded encryptx64.dll, and the name of the file is encryptx64.dll, then the encrypt_path should be './encryptx64.dll'

the reason why this probably isn't in hte readme or tutorial, and why the encrypt files aren't packaged here, is because they are copyrighted material by niantic.

**Comment by Foxbond** [comment]
@Aiyubi I dont see connection

@leclaida Thanks, problem solved.

1. Delete *.pyc
2. Copy encrypt32bit.dll/encrypt64bit.dll
3. In config.py ENCRYPT_PATH = './encrypt64bit.dll'
4. It's working.

**Comment by leclaida** [comment]
np, happy hunting.
