### ISSUE TITLE
/report throws exceptions

### ISSUE THREAD

**Issue by Bifros7** [modrzew/pokeminer#28]
![image](https://cloud.githubusercontent.com/assets/13536271/17087116/bb4b37f8-5202-11e6-956e-b4fe99b5f931.png)
I assume this might happen if there are no STAGE2 Pokemon to show, though I'm not sure.

**Comment by matt-shine** [comment]
Just got this, having only had the runner going for ~5 minutes I'm assuming it's the length_hours var equalling zero. Not sure about OP's case.

**Comment by irrg** [comment]
OP's trace also ends on a division by length_hours, and I had the same issue when I tried this out. So I'd say it's definitely the per_hours calc.

**Comment by modrzew** [comment]
Fixed in 6000ddbd.
