### ISSUE TITLE
Can you send results to a webpage?

### ISSUE THREAD

**Issue by JBCreator30** [modrzew/pokeminer#280]
I understand the web.py allows you to open the map in a web interface, but if I want to access remotely per say through my phone, can I set it to be sent to my personal domain? What I'm trying to do is being able to scan the area I'm usually in, so if I leave the program running on my pc at home I can access it from the internet, plus I want to be able to share it with my buddies

**Comment by modrzew** [comment]
You can run the interface with

```
python web.py --host 127.0.0.1 --port 8000
```

where host is IP app should listen on (optionally domain, not sure if that would work), and port is... well, the port.
