### ISSUE TITLE
Cant run worker.py because steps got removed

### ISSUE THREAD

**Issue by Eduardox** [modrzew/pokeminer#29]
steps got removed so now when I try to run
`python worker.py -st 8`
This pops up
`C:\Users\User\Downloads\pokeminer-master>python worker.py -st 8 usage: worker.py [-h] [--no-status-bar] [--log-level {DEBUG,INFO,WARNING,ERROR}] worker.py: error: unrecognized arguments: -st 8`
Now if I remove -st 8 this pops
`Traceback (most recent call last): File "worker.py", line 658, in <module> spawn_workers(workers, status_bar=args.status_bar) File "worker.py", line 629, in spawn_workers print get_status_message(workers, count, start_time, points_stats) File "worker.py", line 577, in get_status_message messages = [workers[i].status.ljust(20) for i in range(count)] File "worker.py", line 513, in status progress=(self.step / float(self.count_points) * 100) ZeroDivisionError: float division by zero`

**Comment by DavidSelem** [comment]
I wrote python worker.py and it worked, but I don't know how many steps are the bot using

**Comment by Eduardox** [comment]
I cant get v 0.3 to work, but 0.2 does

**Comment by Eduardox** [comment]
fixed with 0.3.1
