### ISSUE TITLE
[Question] Only for datamining? How about a live map?

### ISSUE THREAD

**Issue by cryzies** [modrzew/pokeminer#3]
Is this only for datamining? Will there be a live map I can use to locate pokemon? Hoping to code in some flags for some rare pokemons in an attempt to catch them.

**Comment by modrzew** [comment]
There is a live map, and it even works! Try running `web.py`. Note that autorefresh and other fancy things are not working correctly, so you have to manually F5 it.

**Comment by cryzies** [comment]
Thanks!

**Comment by cryzies** [comment]
@modrzew is there a quick way to disable database entries but keep the live map? Running on a small HD vm

**Comment by modrzew** [comment]
Comment out [line 515 in `worker.py`](https://github.com/modrzew/pokeminer/blob/master/worker.py#L515), or [line 61 in `db.py`](https://github.com/modrzew/pokeminer/blob/master/db.py#L61).

But why would you want to do this? I have over 100k entries in DB and their size is just about 10 MB.

**Comment by cryzies** [comment]
@modrzew is it suppose to error this often?
https://imgur.com/a/we1YH

**Comment by modrzew** [comment]
It is, whenever servers are experiencing issues. Right now I'm unable to login using my normal account on the phone, so it's nothing out of place.
