### ISSUE TITLE
Lat and Lon Gain

### ISSUE THREAD

**Issue by ferazambuja** [modrzew/pokeminer#30]
Could you expand a bit more? I'm never sure how many workers is needed for an area. My educated guess is that the old -st 10 use to be around 2km radius.

**Comment by modrzew** [comment]
To put it simply, 1 degree of lat/lon will mean different distance depending on where you are in the world. For example, longitude starts at about 110 km per degree near the equator and slowly goes toward 0 as you go north/south - where I live, it's about 20 km per degree IIRC. Modifying gain lets you compensate for that to have your points being spread uniformly.
