### ISSUE TITLE
I am getting a login issue is there anything that can be done

### ISSUE THREAD

**Issue by paperc07** [modrzew/pokeminer#33]
I don't know if there is anything you can do but I am getting a login issue and only some of my workers will work . I originally had like 200 but had to keep coming down because it seemed I could only do 10 at a time and now I can't even get 20 to work unless I log into the ones that arent working individually? 

![image](https://cloud.githubusercontent.com/assets/9095222/17091563/819b79ee-5209-11e6-8f76-f00592a44ae8.png)

**Comment by Eduardox** [comment]
Are you sure its a log in issue?
This happens to me too, but closing and reopening seems to work (and after some minutes some workers stop moving)

Also, care to share how to create ptc accounts automatly? I want 200 accounts also :p

**Comment by paperc07** [comment]
I made a tutorial somewhat im stuck at the end and yeah im pretty sure its a login issue, because it cuts out but you can manage to see like invalid login or whatever and then if I go test it with pokefinder its fine and then works thats why I said I didn't know if I had to activate them or something, or maybe do a longer ms login time idk.

https://www.reddit.com/r/pokemongodev/comments/4ug8du/mass_email_creation/

**Comment by paperc07** [comment]
I also noticed I get this if I CTRL+C 

Traceback (most recent call last):
  File "C:\Users\FRU5TRAT3\Desktop\POKE MINERNEW\pokeminer-0.3.1\worker.py", line 658, in <module>
    spawn_workers(workers, status_bar=args.status_bar)
  File "C:\Users\FRU5TRAT3\Desktop\POKE MINERNEW\pokeminer-0.3.1\worker.py", line 630, in spawn_work
ers
    time.sleep(0.5)
KeyboardInterrupt

**Comment by Eduardox** [comment]
This post hast a screenshot of a lot of workers and seems like the same problem #20 
Also, your post got deleted I think. Can you repost or something?

**Comment by paperc07** [comment]
yeah I don't think its the same becuase the never even start and I legit see it say something to do with login, I think its invalid login

**Comment by rizjuan1** [comment]
I have this same issue. It had worked fine earlier in the day with a 8x8 grid. However now when I start it half of my workers stay at 0 to 1%. When I Cntrl+C I get the following. I'm running v0.3:

> Exception in thread worker-34:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "worker.py", line 466, in run
>     self.main(service, api_endpoint, access_token, profile_response)
>   File "worker.py", line 489, in main
>     lon=point[1],
>   File "worker.py", line 546, in process_step
>     profile_response
>   File "worker.py", line 356, in get_heartbeat
>     m5,
>   File "worker.py", line 264, in get_profile
>     return retrying_api_req(service, api, access_token, req, useauth=useauth)
>   File "worker.py", line 148, in retrying_api_req
>     **kwargs
>   File "worker.py", line 187, in api_req
>     r = session.post(api_endpoint, data=protobuf, verify=False)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 518, in post
>     return self.request('POST', url, data=data, json=json, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 403, in send
>     timeout=timeout
>   File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 590, in urlopen
>     **response_kw)
>   File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 369, in from_httplib
>     if not isinstance(headers, HTTPHeaderDict):
>   File "/usr/lib/python2.7/abc.py", line 144, in __instancecheck__
>     return cls.__subclasscheck__(subtype)
>   File "/usr/lib/python2.7/abc.py", line 174, in __subclasscheck__
>     for rcls in cls._abc_registry:
>   File "/usr/lib/python2.7/_weakrefset.py", line 59, in __iter__
>     with _IterationGuard(self):
> TypeError: 'NoneType' object is not callable
> 
> Exception in thread worker-48:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "worker.py", line 466, in run
>     self.main(service, api_endpoint, access_token, profile_response)
>   File "worker.py", line 489, in main
>     lon=point[1],
>   File "worker.py", line 546, in process_step
>     profile_response
>   File "worker.py", line 364, in get_heartbeat
>     heartbeat = pokemon_pb2.ResponseEnvelop.HeartbeatPayload()
> AttributeError: 'NoneType' object has no attribute 'ResponseEnvelop'
> 
> Exception in thread worker-42:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "worker.py", line 466, in run
>     self.main(service, api_endpoint, access_token, profile_response)
>   File "worker.py", line 489, in main
>     lon=point[1],
>   File "worker.py", line 546, in process_step
>     profile_response
>   File "worker.py", line 364, in get_heartbeat
>     heartbeat = pokemon_pb2.ResponseEnvelop.HeartbeatPayload()
> AttributeError: 'NoneType' object has no attribute 'ResponseEnvelop'

**Comment by paperc07** [comment]
ok so I managed to FRAPS it because my stuff goes away idk how @rizjuan1 was able to see his log or mark it. THERE IN ORDER also

![image](https://cloud.githubusercontent.com/assets/9095222/17103146/e8547636-524a-11e6-83c4-b0cacb458cb4.png)


![image](https://cloud.githubusercontent.com/assets/9095222/17103151/f7b1dcea-524a-11e6-87cf-c8e6aa9877ca.png)


![image](https://cloud.githubusercontent.com/assets/9095222/17103167/0b7aaf68-524b-11e6-84a7-358bc42985a4.png)

**Comment by Eduardox** [comment]
Suddenly all my workers stopped working, and they show [W5: LOG IN FAIL]
So yeah, this is a log in issue

**Comment by modrzew** [comment]
[Server status](http://www.mmoserverstatus.com/pokemon_go) says that potatoes are boiling - at least those handling PTC logins. Downtime, ho!

**Comment by paperc07** [comment]
@modrzew  yeah but my accounts aren't working can you please help me to where I can have 40+ google accounts that will work fine?

**Comment by Eduardox** [comment]
@modrzew PTC servers are now fine (kinda) and still 1-5 of my workers are always stuck. Any ideas on what can be going wrong?

**Comment by modrzew** [comment]
I just merged code to master that checks upon workers every 5 minutes and replaces those that are stuck for some reason (either at 0%, or running around and not seeing a single spawn). Please check it out - I'm closing the issue, but feel free to open new one in case there's anything wrong.
