### ISSUE TITLE
Server keeps stopping

### ISSUE THREAD

**Issue by memeshack** [modrzew/pokeminer#35]
I'll have the server running for 20 minutes then this will happen.
http://prntscr.com/bx4wrd
I have 64 workers if that helps at all.

**Comment by modrzew** [comment]
Something probably happened with Pokemon Go servers and reply for an request was malformed. I'll look into that, but I'm not sure whether I'd be able to reproduce it.

**Comment by kravock** [comment]
I'm using Supervisord to automatically restart the worker if it crashes.

**Comment by memeshack** [comment]
How do you have your .conf setup for supervisor? cause everything i try doesnt work.

**Comment by kravock** [comment]
This works for me. You need to change the directory variable to the folder your worker.py is in.

[program:pokeminer]
command=python worker.py
autostart=true
autorestart=true
directory=/var/www/pokemon

**Comment by modrzew** [comment]
I wrapped the request part in worker.py with try..except block and it should catch more exceptions and automatically restart workers - please check it out.
