### ISSUE TITLE
Issue with to old timestamp (sometimes)

### ISSUE THREAD

**Issue by amistad18** [modrzew/pokeminer#36]
I noticed today, while displaying /report, that I have some old timestamp data in the database. Report said that I started to mining since 07.18, while more accrete is that I started on evening 07.23. I'm wondering if this is an issue with the server responses? That game server itself returns wrong data and already expired pokemons? (I think I noticed that on AHAAAAAAA/PokemonGo-Map before, but didn't get in to it too much)

I'm attaching database preview, this is view sorted by normalized_timestamp ... notice the ID, the first database records are with the correct timestamp, and the wrong ones are amongst event the newest ones.

![fireshot capture 14 - phpliteadmin_ - http___localhost_phpliteadmin php](https://cloud.githubusercontent.com/assets/3898985/17105604/4059acce-5288-11e6-92f4-1f34af738405.png)

**Comment by Sigi-cz** [comment]
duplicate https://github.com/modrzew/pokeminer/issues/19

**Comment by modrzew** [comment]
Indeed - closing as duplicate.
