### ISSUE TITLE
5 min spawn chart 

### ISSUE THREAD

**Issue by ferazambuja** [modrzew/pokeminer#37]
I just notice that at my graph shows as a line. It shows spawn seen: 0.

https://dl.dropboxusercontent.com/u/9492397/pokeminer-report/Pokeminer%20Report.html
https://dl.dropboxusercontent.com/u/9492397/Screen%20Shot.png

**Comment by lskupnjak** [comment]
Noticed this as well

**Comment by kravock** [comment]
Same here.

**Comment by 1n9i9c7om** [comment]
As it might help troubleshooting;
I've noticed that this is occuring on my setup that uses sqlite. My other setup that uses MySQL (and scans a much larger area) works (except for some crashes, heh): http://i.1n9i9c7om.com/ETWZf1.png

**Comment by Aiyubi** [comment]
submitted bugfix #68

**Comment by modrzew** [comment]
#68 was just merged to master, will be released together with v0.4.
