### ISSUE TITLE
Status on worker.py

### ISSUE THREAD

**Issue by ferazambuja** [modrzew/pokeminer#38]
Is there any way to have a live log/debug showing on worker.py?
Or at least a bit more of info.

`PokeMiner	running for 0:02:51.943190
3 workers, each visiting ~116.666666667 points per cycle (min: 112, max: 126)
Status: Scanning/Fail to Connect/Offline/Error`

As right now it's hard to see when the servers are down. It's a minor thing...

**Comment by DavidSelem** [comment]
I think you mean this: python worker.py --no-status-bar

**Comment by ferazambuja** [comment]
that was easy 👍
