### ISSUE TITLE
worker has bugs 

### ISSUE THREAD

**Issue by KenUdigIT710** [modrzew/pokeminer#4]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discordapp.com/invite/qbpVH6b).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of Python:

### Steps to reproduce
1.run worker.py
2.
3.

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
its on line 100 but that's not the only one holding me up 

File "worker.py", line 100
    print '[-] {}'.format(message)
                 ^
SyntaxError: invalid syntax

**Comment by modrzew** [comment]
Please use Python 2.7, and not Python 3. As I'd love to use Python 3, right now I don't have resources to rewrite everything.

**Comment by KenUdigIT710** [comment]
thanks for the heads up but i am still having issues  with request  
Traceback (most recent call last):
  File "worker.py", line 8, in <module>
    import requests
ImportError: No module named requests

C:\Users\nek95\Desktop\pokeminer-master>python worker.py -st 8
Traceback (most recent call last):
  File "worker.py", line 13, in <module>
    import werkzeug.serving
ImportError: No module named werkzeug.serving

**Comment by modrzew** [comment]
Please check out [the guide on Reddit](https://www.reddit.com/r/pokemongodev/comments/4tz66s/pokeminer_your_individual_pokemon_locations/d5lovb6).
