### ISSUE TITLE
Report - area always = 96 square km

### ISSUE THREAD

**Issue by TheMainAttractionHomie** [modrzew/pokeminer#42]
Wonderful reporting system, thank you! I noticed that on my reports and your own posted on Reddit/imgur that the {{ area }} is always 96 square km.

**Comment by modrzew** [comment]
Yeah, I hardcoded it because of lack of time (together with city name). Nonetheless, @pdong did PR #34 that solves the issue, I'll test it and hopefully merge when I have spare time.

**Comment by modrzew** [comment]
PR #34 was just merged to master.
