### ISSUE TITLE
detect broken workers and restart them

### ISSUE THREAD

**Issue by techdough** [modrzew/pokeminer#46]
I think a good enhancement would be if program can detect stuck workers it can restart them. Here are 2 examples I see stuck workers:

1) worker stuck at P0,0%
2) worker stuck at PX,Y% where x and y are just some numbers > 0 that never update. 

you could implement a check that if than worker hasn't updated in 3 minutes, restart it. 

This area has generally become better and better each release.

this seems to be less of a problem with lower worker counts. I never see it with 10 but usually see it with 20+

Thank you!

**Comment by Aiyubi** [comment]
had the same issue. Turned out when I looked at the error messages that it was an issue with database access not being safe for threads

I uploaded a possible fix as pullrequest #47

**Comment by techdough** [comment]
ty i will try it out. maybe this is a dupe of my other issue i reported #44

**Comment by modrzew** [comment]
So this has been done for long, long time now. I suck at managing Github issues.
