### ISSUE TITLE
Google analytics with web.py?

### ISSUE THREAD

**Issue by memeshack** [modrzew/pokeminer#48]
Is this possible? If so how would I go about doing this

**Comment by Aiyubi** [comment]
the way I understand google analytics: you add a script at the end of your website that does everything. So adding it should be no problem.

Check the offical google guide:
https://support.google.com/analytics/answer/1008080?hl=en

**Comment by modrzew** [comment]
And why would you want Google Analytics in web.py?

Besides, if you're hosting pokeminer somewhere, you can add it to the template manually.
