### ISSUE TITLE
'You have exceeded your daily request quota for this API.'

### ISSUE THREAD

**Issue by Eduardox** [modrzew/pokeminer#49]
After a while of running I get this error of exceding the limits of request, checked in the api interface and indeed it has a 2500 request per day (can get more if I pay, not sure). Any way over this that doesnt involve making a new api key each 3-5 hours?

**Comment by GaelicGamer** [comment]
Are you using your own java-api key?  I'm using my own key I'm nowhere near that.

**Comment by Eduardox** [comment]
@GaelicGamer Yeah, figured out the problem. I have pokeminer + a bot leveling and stuff running at same time. If I only run pokeminer or only the bot I don't have any problems, but running both brings this error.
So I need one project for miner and another one for the bot to stay below the daily limit (different keys) :)

**Comment by paperc07** [comment]
@Eduardox  I am using necrobot and it doesn't even make me use a api key that im aware of
