### ISSUE TITLE
main() error

### ISSUE THREAD

**Issue by Mila432** [modrzew/pokeminer#5]
### Steps to reproduce
Inside:
if -steplimit2 / 2 < x <= steplimit2 / 2 and -steplimit2 / 2 < y <= steplimit2 / 2:
		lat = x * 0.0025 + origin_lat
		lon = y * 0.0025 + origin_lon
if you do not enter this if both values are undefined  
possible solution:
else:
		lat=origin_lat
		lon=origin_lon

**Comment by modrzew** [comment]
Thanks, I'll take care of it.

**Comment by modrzew** [comment]
This is going to be refactored in #55.
