### ISSUE TITLE
python worker.py not working anymore

### ISSUE THREAD

**Issue by elx0r** [modrzew/pokeminer#50]
I've checked and rechecked OVER and OVER again and it doesn't work! It worked the first time, but then when I moved onto this version it didn't! Reused the older one and it also didn't work anymore! All I did was changing the cords and nr of workers from 25 to 168!

Here is the beginning of my config:

> DB_ENGINE = 'sqlite:///db.sqlite'
> MAP_START = (51.512958, -0.129338)
> MAP_END = (51.504109, -0.105614)
> GRID = (13, 13)

And here is the output:

```
Traceback (most recent call last):
 File "worker.py", line 659, in <module>
   spawn_workers(workers, status_bar=arg
 File "worker.py", line 630, in spawn_wo
   print get_status_message(workers, cou
 File "worker.py", line 578, in get_stat
   messages = [workers[i].status.ljust(2
 File "worker.py", line 514, in status
   progress=(self.step / float(self.coun
eroDivisionError: float division by zero
```

**Comment by Aiyubi** [comment]
your output is missing a lot of characters

but your problem: you need 1 more worker
13*13 = 169
with only 168 workers 1 slot is empty

**Comment by Aiyubi** [comment]
oh and in case this was not the error: your lat/long gain would be interesting for solving this

**Comment by elx0r** [comment]
I honestly didn't understand a word of what you said!
This thing worked the first time.Then it didn't
Also the lat/long gain....what are these? They aren't shown anywhere!!!!

**Comment by Aiyubi** [comment]
* about the characters: look at it. The end of the lines is cut out.
* about the worker: for 13x13 you need 169 workers. You are telling you only have 168. Either change your grid or add 1 more worker
* about lat/long gain. It is in the samle config in the readme file: 
https://github.com/modrzew/pokeminer/blob/master/README.md
just before the accounts

**Comment by modrzew** [comment]
Looks like an issue with config. Closing, feel free to open another one in case there are further problems.
