### ISSUE TITLE
change to hex grid

### ISSUE THREAD

**Issue by Sigi-cz** [modrzew/pokeminer#57]
most scanners seem to use it. And some of them are crazy fast ( https://github.com/favll/pogom )

**Comment by ardeaf** [comment]
Hex is quite a bit faster but much more inaccurate.

**Comment by modrzew** [comment]
I also saw reports about it being not as accurate. Moreover it also uses way more computation to generate hex grid. I'll look into it, but it's low on my priority list.

**Comment by Aiyubi** [comment]
@modrzew it is a one time generation and really not that much calculation more.

I would not say it is less accurate. Everything depends on the radius you expect as scannerrange.

I would like to give this a try. Will report back once I made some progress

**Comment by modrzew** [comment]
So this just landed in master in as 3f6aec6639ebeddb7d72beef05e6cb512474071f. It was fun, doing math once in a while!
