### ISSUE TITLE
More than 50% of the workers stay at 0%

### ISSUE THREAD

**Issue by elx0r** [modrzew/pokeminer#58]
As the title says. I'm using 156 workers (12,13)
and more than half of them stays at 0% and in the map no pokemon shows on those pointers...what do I have to do?

EDIT: looks like when I restart it, in the beginning everything works perfectly...so I guess they stop working after a while

**Comment by pdong** [comment]
If you look at `worker.log` do you see any issues?  Are you using google or PTC auth?  If a bot fails to re-authenticate it will sometimes get stuck and PTC is pretty flaky.

**Comment by elx0r** [comment]
The only issue I saw is than after 6 hours...no pokemon was found by any worker.And i'm using PTC
I think we need a more stable DB perhaps :(

**Comment by luzer** [comment]
same here

**Comment by MEGAMERICAN** [comment]
I am having the same problem right now with only 10 workers. I restart the program and anywhere between 2 - 5 will be stuck at 0%. Each time different ones do not work. They are all PTC accounts, so I expect that it is server issues.

**Comment by tmcfl** [comment]
I've noticed this same issue. Looks like the workers occasionally get hung up while (re)connecting, and there's no process to check whether they're hung and try connecting again. So if the process is run long enough, the amount of workers stuck at 0% steadily increases.

Examining the `worker.log`, the last/only message for a worker that's stuck at 0% is `Starting new HTTPS connection(1): sso.pokemon.com`. 

Knowing that PTC logins are unreliable, I'd like to add some logic to check how long a worker has been stuck in their current state and restart the worker if it's above a certain threshold (like 5 minutes).

**Comment by modrzew** [comment]
Bunch of changes just landed in master, especially mechanism that restart workers that don't do anything for more than 5 minutes (either are frozen, or are running around without seeing any spawns). Please check it out.
