### ISSUE TITLE
expired pokemon not removed from map?

### ISSUE THREAD

**Issue by gardnert** [modrzew/pokeminer#6]
Clicking on a pokemon shows it as being expired, but doesn't remove it form the map.

Refreshing removes expired pokemon from the map, but the auto-refresh from the web.py doesnt seem to be auto-refreshing at all

**Comment by modrzew** [comment]
Yeah, good amount of interactivity (like auto refresh) is broken on the frontend right now. I'm intending on fixing it soon.

**Comment by georgi-huklev** [comment]
There is a typo in web.py:

`@app.route('/config')
def config():
    """ Gets the settings for the Google Maps via REST"""
    center = {
        'lat': DOUBLE_LAT,
        'lng': DOUBLE_LON,
        'zoom': 15,
        'identifier': "fullmap"
    }
    return json.dumps(center)`

Should be original_lat and original_lon instead of DOUBLE_LAT and DOUBLE_LON respectively.

After it was fixed autorefresh and old pokemons removal worked fine.
