### ISSUE TITLE
[suggestion] move away from grid

### ISSUE THREAD

**Issue by Aiyubi** [modrzew/pokeminer#61]
currently the grid is what is limiting the number of workers.
number_of_workers_active = Grid[0]*Grid[1] 

I think it would be better to spawn as many workers as ACCOUNTS

How to do this easy:
1. create all locations to scan
2. sort them in a way that there is a single path (like this https://goo.gl/BBnLZN )
3. seperate the path in len(ACCOUNTS) parts
4. spawn 1 worker per path segment

This would also work with a different basegrid (like hexagon)

**Comment by Bifros7** [comment]
I like the flexibility of rows and columns. Sometimes I want to scan an area in something like a (5, 20) grid.

**Comment by Aiyubi** [comment]
@Bifros7 what do you think is the difference?

**Comment by Bifros7** [comment]
@Aiyubi Maybe I misunderstood your suggestion, I thought you wanted to always create a square grid. If that's not the case, I'm all for it.

**Comment by Aiyubi** [comment]
@Bifros7 it really is just about the distribution of work to workers - nothing else

**Comment by Sigi-cz** [comment]
I also would remove the grid. Just take the border coordinates, calculate cells and assign available workers. If there are not needed workers (50 cells, 100 workers) just let the rest slack :)

**Comment by modrzew** [comment]
I like the idea of creating the path. I'll look into it.

**Comment by GaelicGamer** [comment]
I'll see if I can squeeze this into my current pull, not a fan of letting workers slack though, rather have less points per worker and quicker scans, hardware is cheap now-and-days.
