### ISSUE TITLE
logging data for later analysis

### ISSUE THREAD

**Issue by Kostronor** [modrzew/pokeminer#62]
Hello there,

we are currently creating a big collection of pokémon spawns/nests and want to ask popular pokemon maps to share their data with us.

for reference: 
https://www.reddit.com/r/TheSilphRoad/comments/4uqlet/pokelyzer_setup_instructions_a_tool_for_finding/
https://github.com/Kostronor/pokelector

What we would need are:

- A log file created that adds a new line for each pokémon found.If possible removing hearthbeat updates. 
- maybe an option to push all found pokémon over a socket (if the user wants that)

what we need is a data object having these properties:

```
pokemon_id = int(data['pokemon_id']) # the pokemon number
last_modified_time = int(data['last_modified_timestamp_ms']) # when you received the pokemon from pogo-servers
time_until_hidden_ms = int(data['time_till_hidden_ms']) # the time until the mon is hidden
encounter_id = str(data['encounter_id']) # the encounter id from pogo
spawnpoint_id = str(data['spawnpoint_id']) # the spawnpoint id from pogo
longitude = float(data['longitude']) # longitute of the spawn
latitude = float(data['latitude']) # latitude of the spawn
```

Sending a json object would be best but other formats are fine too. If you can give me a hint where to look for a pokemon received event, I could submit a pull request.

**Comment by modrzew** [comment]
Why don't you just connect to the database and transform data in whatever way you want?

**Comment by modrzew** [comment]
By the way, the only field that's really missing now is encounter ID, and that was already reported in #15.

**Comment by Kostronor** [comment]
The plan was to have a small script push new data every x hours (or use events from within the map). Connecting to the db means (with sqlite) that the user has to quit the map for data upload, something we want to prevent.

**Comment by modrzew** [comment]
If I understand correctly the problem lies in your application's architecture, and not pokeminer.

**Comment by Kostronor** [comment]
Pokeminer is using sqlite, right? And sqlite cannot be accessed by two programs at the same time. So to access the data pokeminer is accumulating we need to interface with your program, not the database.

And we are asking if it would be possible to help you create such an interface.

**Comment by modrzew** [comment]
Pokeminer is using [any database engine supported by SQLAlchemy](http://docs.sqlalchemy.org/en/latest/core/engines.html).

And [who said SQLite can't be accessed by multiple processes at the same time](https://www.sqlite.org/faq.html#q5)? Actually, pokeminer's multiple workers are able to access it using multiple connections over multiple threads. I think default connection pool in SQLAlchemy has up to 20 connections.

**Comment by Kostronor** [comment]
Ahh I see! Would it be possible to add an upload config option to pass data on for further analysis? If yes, where in your codebase is the point to insert new pokemon into the database?
