### ISSUE TITLE
Live map don't work.

### ISSUE THREAD

**Issue by rnunojoao** [modrzew/pokeminer#63]
Here's a image: http://prntscr.com/bypvzd

**Comment by Bifros7** [comment]
Is your worker running? Did you initialize your db by running
```
import db
db.Base.metadata.create_all(db.get_engine())
```
?

**Comment by bravelittletoastr** [comment]
Where is your static folder at?

**Comment by rnunojoao** [comment]
I don't what did I did but it's working now!

**Comment by modrzew** [comment]
Yay! :+1:
