### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by Kostronor** [modrzew/pokeminer#64]
I forked your repo and added python3 support for it. Would it help to make a pull request?

**Comment by fu20161234** [comment]
Why not just submit a pull request and let him decide if he wants it? This isn't an issue...

**Comment by Kostronor** [comment]
@fu20161234 many maintainers like it to have an issue to the pull request, so asking first is just being nice. If he does not want my pull request, python3 support is an issue.

**Comment by modrzew** [comment]
@Kostronor could you check whether the newest master also can be easily ported to py3? Specifically pgoapi library. If so then I'll surely dedicate some time for that - I didn't really think about it before, but Python 2 should be treated as a relict of the past, and Python 3 should be the only way to go.

**Comment by hador** [comment]
@modrzew all dependencies support python3. Your code is actually pretty much python3-ready, it just needs a few one-line changes. I can create a pull-request against the most recent version if you want, or you could check out the changes in my fork and cherry pick them yourself.

**Comment by modrzew** [comment]
...seriously? 01baeac1ec3fb90870e05cf817331b72cc5ebcf8 was everything needed?

**Comment by hador** [comment]
Pretty much, however on python3 logging is now broken (the formatting string isn't being interpreted at all). You should remove the style= argument in your logging.basicConfig statement.

**Comment by Kostronor** [comment]
I had a fix for that, you have to change the format character. I'll create a pr
