### ISSUE TITLE
worker.py stopping

### ISSUE THREAD

**Issue by DerBoss069** [modrzew/pokeminer#69]
After a few minutes my worker.py keep stopping with this infos:

```
Traceback (most recent call last):
  File "worker.py", line 659, in <module>
    spawn_workers(workers, status_bar=args.status_bar)
  File "worker.py", line 630, in spawn_workers
    print get_status_message(workers, count, start_time, points_stats)
  File "worker.py", line 578, in get_status_message
    messages = [workers[i].status.ljust(20) for i in range(count)]
  File "worker.py", line 508, in status
    if self.error_code:
AttributeError: 'Slave' object has no attribute 'error_code'

```

Anyone know how can i fix this?

**Comment by Bifros7** [comment]
Most likely an issue with the PGO servers. If it bothers you, you can wrap it in an infinite while loop like this:
```
while true; do python worker.py; done
```

**Comment by DerBoss069** [comment]
I install supervisor for ubuntu and let him do a restart if it crashs :)

**Comment by modrzew** [comment]
@DerBoss069 does it happen on the most recent master? It's definitely not an issue with PGO servers, but if memory servers me right I also fixed something similar recently.
