### ISSUE TITLE
Tuple object

### ISSUE THREAD

**Issue by Zyahko** [modrzew/pokeminer#70]
When I do the "import db" while following /u/gprez's great tutorial on Reddit. It gives me an error for one of my accounts and says this:

>>> import db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "db.py", line 17, in <module>
    import config
  File "config.py", line 10, in <module>
    ('username', 'password', 'google')
TypeError: 'tuple' object is not callable

**Comment by fu20161234** [comment]
Can you share your whole config? I'd bet you have an extra comma or are missing one somewhere.

**Comment by Zyahko** [comment]
Yea after looking at the config file it seems that I had forgotten a comma at the end of the line 9
