### ISSUE TITLE
New config.py requirements

### ISSUE THREAD

**Issue by nathaned** [modrzew/pokeminer#72]
Looks like you've added a few new items to config requirements:

- CYCLES_PER_WORKER
  - I've looked into the older version and it looks like **3 was the default before**, so I'll use that unless it is better to use something else.
- LAT_GAIN / LON_GAIN
  - Again, found the defaults from the previous version: 
    - LAT_GAIN: 0.0015
    - LON_GAIN: 0.0025
  - Could someone state how to calculate the necessary Lat/Lon gains for a certain area? From what I understand, I should use lower values than before since the scanning radius changed from 100m to 70m, is that correct?

**Comment by MEGAMERICAN** [comment]
It looks like you are correct for lat_gain/lon_gain. My 30 bots are definitely not catching as large an area as they were before.

**Comment by childrscott** [comment]
Anyone else have any ideas on this? What have you guys tried?

**Comment by nathaned** [comment]
I had the great idea to waste a bunch of time on this because why not. 

So obviously there's some basic geometry that says that if you make a little square out of four circles, you want the inside corners of each circle to touch in order to cover all of the area. I calculated that since each circle has a radius of 70m, diagonal radii should be 140m apart, with a 45 degree angle between them.

So basically, adjacent circles should be spaced 70*sqrt(2) = **98.9949 meters away from each other horizontally/vertically**. You can then go to Google Maps and right click to measure ~95 meters (less to be safe) and if you click on the map a little window pops up on the bottom which gives the Lat and Long. So this is a kinda basic way to get the gain values (by finding difference between lat/long) in your area.

So I thought it would be an _excellent_ idea to waste an incredible amount of time writing [a little JS Fiddle page to find the exact values to set](https://jsfiddle.net/m6nzLmna). Enter your Lat/Long and play around with the gain values in the bottom left (javascript) window. You have to press run in the top left for it to reload. There's a little tooltip to make sure that your circles are the right angle from each other. Zoom in a lot to the center to see if you need to increase/decrease the gain values to minimize the area covered by all four circles without having a space that isn't covered (_it's fun!_).

I don't even live in LA but I calculated the gain values for that area.

Finally, I'd suggest the following values as long as you don't live too close to either of the poles/equator:
- LAT_GAIN = 0.00085
- LON_GAIN = 0.00095

_You could probably get away with higher values (I've attempted to max them out in my link), but those values should be safe._

**Comment by Sigi-cz** [comment]
yeah. letting user to set those is not best idea. This is how my setup looks while using defaults ...
http://imgur.com/x8pFIAo
var START_LAT = 49.545294
var START_LON = 18.211099
var LAT_GAIN = 0.0015
var LON_GAIN = 0.0025

**Comment by Aiyubi** [comment]
@Sigi-cz remember the defaults are based on the old 100m radius. With that it looked way better

**Comment by modrzew** [comment]
I added new toggle button to the live map that shows/hides workers, and more importantly - shows also scan area for all of the points. It's in master and will be released in v0.4.

**Comment by fu20161234** [comment]
@nathaned I have way more than 4 workers (25-75 depending on the area) and am trying to find good values. When I used the values you suggested, my points per cycle went up from 200 to 1000. I'm trying to scan a much larger area than you are proposing, any suggestion on how to find proper values?

**Comment by nathaned** [comment]
@fu20161234 did you use the link I posted? It should scale no matter how many workers you use

**Comment by fu20161234** [comment]
@nathaned Am I missing something? You're talking about this, right? https://jsfiddle.net/m6nzLmna/

So I put my start lat and lon, but I don't see anywhere to specify the end location and/or number of workers. What am I doing wrong?

**Comment by Aiyubi** [comment]
@nathaned you are supposed to edit lat/long gain to find the values

**Comment by nathaned** [comment]
@fu20161234 Number of workers shouldn't matter. Just play with the gain values to ensure that the circles all overlap in the middle.

**Comment by vDrag0n** [comment]
thanks for the links, i've ammended my lat/long gains to be more accurate.  but scan speeds per cycle are much slower due to the increased point demands.  

Have a look at the hex algorithms, the argument is there is less overlap compared to grids, and thus faster cycles.

**Comment by fu20161234** [comment]
Gotcha. I was able to shave a little time off, but still a huge increase in number of workers required :/ I have no desire to make that many more accounts.

**Comment by VirtualSatai** [comment]
@fu20161234 You can easily create them using a tool like: https://github.com/ocjd/ptc-account-creator

**Comment by fu20161234** [comment]
Finally, thanks! I had found a couple online that were just not working or didn't validate, but if that one works I'll do that! Thanks a bunch!

**Comment by GaelicGamer** [comment]
This can probably be closed since the change to using the radius instead of the lat/long gains.
