### ISSUE TITLE
install requirements.txt git clone command error

### ISSUE THREAD

**Issue by Mikeboyslim** [modrzew/pokeminer#73]
Running fresh install `pip install -r requirements.txt` nets me 
`Error [Error 2] The system cannot find the file specified while executing cammand git clone -q git://github.com/tejado/pgoapi.git "MYPATH\pokeminer-master\src\pgoapi.git"
Cannot find command 'git'`

I have Python 2.7 and pip is up to date. I have manually installed the api manually to bypass that part of the installation, but nets me another error `Command "python setup.py egg_info" failed with error code 1 in "MYPATH\pokeminer-master\src\pgoapi\`

**Comment by Aiyubi** [comment]
did you clone the pokeminer git or download the zip file?
looks to me like you do not have git in your path?
Also what is your OS?

**Comment by modrzew** [comment]
I changed `requirements.txt` so that pgoapi is installed over HTTP, and not git. Please check out 6e4e30f39572c02a10c1e2e780c663974a529945, it's in master.
