### ISSUE TITLE
Scan Radius

### ISSUE THREAD

**Issue by GaelicGamer** [modrzew/pokeminer#74]
Hey Guys, trying to figure out if anything needs to be done to accommodate the new scan radius of 70m against the previous 100m?

**Comment by Aiyubi** [comment]
adjust your lat/long gain. See #72 discussion

**Comment by modrzew** [comment]
New button for showing/hiding workers, together with their scan area, was implemented in f99f577c458be586d21c1a19ea5070052051a1cb and will be released with v0.4 soon. You can check it out.

**Comment by GaelicGamer** [comment]
Thanks mate, appreciate the direction.
