### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by MrYadro** [modrzew/pokeminer#76]
I'm not sure if it's pokeminer bug or pokeapi.

I'm trying to login 16 of my accounts which look like:
--------------1
...
--------------16

login and pass is the same.

But for no reason starting after account number 10 they are fail to login.
What i found if i have password longer then 15 symbols it always fails to login.

P.S. and ofc stripping last symbol fixes the issue.

**Comment by modrzew** [comment]
Are you using PTC? I remember some old code in PokemonGo-Map that truncated password to first 15 characters for some reason and used that to login. Try doing that in your config and see whether it helps.

**Comment by MrYadro** [comment]
@modrzew yea, i just remembered that, and it fixed the issue. You had to strip it.
