### ISSUE TITLE
Weird data

### ISSUE THREAD

**Issue by MrYadro** [modrzew/pokeminer#78]
I'm having bunch (about 300) of pokemons spawned with despawn time 1468878815 is that a bug, or niantic trying to add some "noise" in pokemon spawns.

Could anyone confirm that?

**Comment by modrzew** [comment]
Those are 30min/45min spawns. Which version are you using? I realized I may have removed code that prevented them from being put in the database when I moved to pgoapi.

**Comment by MrYadro** [comment]
I'm using latest code from you repo and pgoapi from requirements.txt

**Comment by modrzew** [comment]
Yeah, that explains it. For now just remove those records from database manually when analyzing data/generating reports. Those spawns will be added as normal when expiration time goes under 15min, so you won't loose data about sighting (provided that you run workers for long enough).

**Comment by modrzew** [comment]
Fix added to master, aaaaand it was just released together with v0.4.
