### ISSUE TITLE
Scan radius decreased from 100m -> 70m

### ISSUE THREAD

**Issue by vDrag0n** [modrzew/pokeminer#79]
Has pokeminer been amended to account for the changes yet?

Also are there any plans on changing the algorithm to a hexbased search algorithm?

**Comment by GaelicGamer** [comment]
This is addressed in #72 I had the same thought process seeing that last night, and there is another issue already about the hexagonal scan #57

**Comment by modrzew** [comment]
Long story short: amend it yourself by using `LAT_GAIN` and `LON_GAIN`.

Using hexagons seems like a more challenging task than just creating a grid, and I'll definitely look into it, since who doesn't like challenges?

**Comment by fu20161234** [comment]
I went with default values suggested elsewhere, and unless something else submitted changed the workers scanning, I went from 200 points per cycle to 1k... we could use a way to determine proper values.

**Comment by GaelicGamer** [comment]
That would probably be accurate if you don't want to miss anything, otherwise the javascript posted in #72 would be the closest thing to help you figure out what you want.

**Comment by fu20161234** [comment]
That's just an insane increase, I'd have to create quadruple the amount of accounts I was using before...

**Comment by pokemonracer** [comment]
I got +120 workers for 7 square km area. Is that overkill? Not sure if i can expand the area without loosing  real time info of pokemons.

**Comment by modrzew** [comment]
I'd say it's an overkill. I'm using similar number for 130 square km.
