### ISSUE TITLE
How does step work?

### ISSUE THREAD

**Issue by cryzies** [modrzew/pokeminer#8]
DB_ENGINE = 'sqlite:///db.sqlite'
MAP_START = (33.038946, -117.300476)
MAP_END = (32.433643, -116.863770)
GRID = (4, 5)

Delta Latitude = 0.605303
Delta Longitude = 0.436706

==========

Currently I have step set to 8, and from the command line it says it's looping:step x of 64. So does that mean step is a square that the accounts will go through? The accounts won't figure out the steps required to traverse the entire grid?

I'm trying to figure out how much latitude/longitude a step will cover so I can put the exact number in rather than guestimate and wait for it to traverse all steps to confirm. 

===========

Also I'm creating a massive amount of PTC accounts, let me know if you'd like me to make some for you, I can script the the account creation but I'll leave the account activation up to you, it'll be a temporary email service. I'm planning on splitting my grid into a 10 x 10, so 100 accounts, will the miner be able to handle that many? Should I use less?

Cheers

**Comment by cryzies** [comment]
Just to add:

I noticed that the loop was going to 64 but the circle of Pokemon found was relatively close to the starting points of the tiles. Also, how come some of the grids don't work? I've left it on for 6 hours now and still some of the grids are empty.

**Comment by cryzies** [comment]
https://imgur.com/a/UAjIH

**Comment by cryzies** [comment]
Just confirmed that you don't need to activate accounts to use them in Pokemon Go (weird I know). If you need some @modrzew let me know.

**Comment by rollin** [comment]
Steps came from the master project. 5 steps is approximately a 1.2km radius. This detemines how far each account will search around its pin.
I guess that for the data collection task the full cycle shouldn't be greater that 15 minutes (pokemon despawn time). I have 9 accounts going for 14 steps. It takes 13 minutes from start to finish. Maybe it would be slower during the server peak time.

As for activation, the PTC says that accounts need to be activated in 2 days time until then they are fully functional.

**Comment by cryzies** [comment]
http://imgur.com/Y6Lpdq8

144 accounts!

**Comment by modrzew** [comment]
As @rollin wrote step is a remnant of PokemonGo-Map, and I'll be removing it in favor of each worker visiting all places in its "square".

**Comment by cryzies** [comment]
@modrzew what do you think is more efficient, increasing the number of accounts or increasing the step size? Efficient as in CPU use, 144 accounts at 16 step is pushing 30% CPU load already, and 16 step takes way longer than 15 minutes to complete a cycle :-1:

**Comment by modrzew** [comment]
Well, that's the question of whether you want the data to be fresher, or to have lower CPU load - for me it's definitely fresher data, I'm running it on a server I don't use that much so higher load is not a problem for me.

Workaround right now may be waiting until all workers finish one cycle (go through all steps) and load live map via web.py - if you see gaps between rectangles of Pokemon, then you need more workers, or increase step size.

**Comment by cryzies** [comment]
So more accounts will give fresher data and a bigger step will lower load?

**Comment by rollin** [comment]
> So more accounts will give fresher data and a bigger step will lower load?
seems so.

@cryzies may you help me with registering a bunch those PTC accounts?
wubdawubdawub@gmail.com

**Comment by cryzies** [comment]
Yea, how many do you need

**Comment by paperc07** [comment]
can you help me with some accounts lol I think I only need about 100 max maybe less im just trying to cover to areas? my skype is paperc07 email paperc07@yahoo.com lmk plz and ty

**Comment by rollin** [comment]
@cryzies about 50, with e-mails like afhsdfhyjsrgftyhfyn**1**@mailinator.com and so forth to validate them with ease. Thank you!
