### ISSUE TITLE
All pokemons are expired while viewing the map on my phone

### ISSUE THREAD

**Issue by DavidSelem** [modrzew/pokeminer#80]
In my desktop its showed correctly,  but in my phone it's not, what could be causing this ?

**Comment by modrzew** [comment]
No idea. Lack of Internet connection? Some JS error?

What phone and browser do you use?

**Comment by plague180** [comment]
My brother was also having this issue. Works fine on my iphone, but not on his android(one of the new notes) since I updated to 0.4.

**Comment by DavidSelem** [comment]
I'm on a nexus 5x,  using Chrome,  tested in local wifi and 4G
