### ISSUE TITLE
[Suggestion] Alerts

### ISSUE THREAD

**Issue by jane0815** [modrzew/pokeminer#81]
Is it possible to add alerts to pokeminer?

**Comment by VirtualSatai** [comment]
I doubt it will happen since the point of this project is to gather data, not to be a map. Since you have a database with data, you can just query it frequently to get the data about Pokémon you're interested in and have that alert you.

**Comment by jane0815** [comment]
The maps all do not work very well since the api was changed. Pokeminer map is the only one that shows all pokemons for me. So i thought it would be nice to get alerts from it too. I am not a coder and don't know how to get that infos from the database.

**Comment by modrzew** [comment]
If you want alerts on a live map, then you can hack your way in `templates/map.html`. But @VirtualSatai is right, live map is just an addition, and pokeminer focuses on filling the database.

[I actually did a simple version of notification system before](https://github.com/modrzew/pokeminer/commit/a079cc9fc6732455dda9d03331f8dd2ca543d6b8), you can use that as a hint what & where to modify.
