### ISSUE TITLE
Error 2 when installing requirements.txt

### ISSUE THREAD

**Issue by Incestosaurus** [modrzew/pokeminer#82]
I put the following into a command window at pokeminer-0.4:
`"C:\Python27\Scripts\pip2.7.exe" install -r requirements.txt`

and I get the error :
` Error [Error 2] The system cannot find the file specified while executing command git clone -q https://github.com/tejado/pgoapi.git "C:\Users\The Harbinger\Desktop\Desktop Junk\pokeminer-0.4\srs\pgoapi"
Cannot find command 'git'`

Anyone know how to fix? I'm running windows 10

**Comment by DavidSelem** [comment]
You need to install git first

**Comment by Incestosaurus** [comment]
Where do I install that? Sorry I'm pretty new to Python
