### ISSUE TITLE
Worker.py error every 30 seconds or so

### ISSUE THREAD

**Issue by kravock** [modrzew/pokeminer#83]
Since some of the latest changes I'm getting the following error in my worker.log every 30 seconds or so 
`[2016-07-31 10:50:30,352][  worker-3][   ERROR][L 155] A wild exception appeared!
Traceback (most recent call last):
  File "worker.py", line 150, in run
    self.main()
  File "worker.py", line 192, in main
    map_objects = response_dict['responses'].get('GET_MAP_OBJECTS', {})
TypeError: sequence index must be integer, not 'str'
`
Also, I'm noticing a much higher CPU usage than before. Anyone else noticing this?

**Comment by amistad18** [comment]
> Also, I'm noticing a much higher CPU usage than before. Anyone else noticing this?
Yep, I noticed the same. I was using 2 vCPU lunanode VPS, and the average usage when all 45 workers were working was around 1.50 ... after newest version, it jumped to ~5.00. So I had to decrease number of workers, to 30 to fit into max 2.0 average CPU usage :(

**Comment by kravock** [comment]
Looks like my CPU issues were related to some changes I had made in my fork. @amistad18 I could do you a deal on a VPS in Australia if you're interested?

**Comment by amistad18** [comment]
@kravock Thanks for offer, but for me this is other side of the globe ... Poland here ;)

Anyway, I managed to lover the CPU usage by over a half, by disabling some unnecessary workers from the grid.
