### ISSUE TITLE
Workers getting killed?

### ISSUE THREAD

**Issue by pokemonracer** [modrzew/pokeminer#84]
Any idea why that happens? There was nothing in worker.log.

**Comment by pokemonracer** [comment]
Last lines before it gets killed:

> Line 477210: [2016-07-31 04:40:11,157][  worker-1][    INFO][L 211] Creating a new direct request...
> 	Line 477211: [2016-07-31 04:40:11,157][  worker-1][    INFO][L 218] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
> 	Line 477212: [2016-07-31 04:40:11,157][  worker-1][    INFO][L 179] Execution of RPC
> 	Line 477213: [2016-07-31 04:40:11,158][  worker-1][    INFO][L 788] Starting new HTTPS connection (1): pgorelease.nianticlabs.com
> 	Line 477272: [2016-07-31 04:40:11,486][  worker-1][    INFO][L 187] Cleanup of request!
> 	Line 477273: [2016-07-31 04:40:11,486][  worker-1][    INFO][L 182] Point processed, 0 Pokemons seen!
> 	Line 477330: [2016-07-31 04:40:11,891][  worker-1][    INFO][L 155] Visiting point removed (removed)
> 	Line 477331: [2016-07-31 04:40:11,891][  worker-1][    INFO][L 211] Creating a new direct request...
> 	Line 477332: [2016-07-31 04:40:11,891][  worker-1][    INFO][L 218] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
> 	Line 477333: [2016-07-31 04:40:11,892][  worker-1][    INFO][L 179] Execution of RPC
> 	Line 477334: [2016-07-31 04:40:11,894][  worker-1][    INFO][L 788] Starting new HTTPS connection (1): pgorelease.nianticlabs.com
> 	Line 477390: [2016-07-31 04:40:12,226][  worker-1][    INFO][L 187] Cleanup of request!
> 	Line 477391: [2016-07-31 04:40:12,226][  worker-1][    INFO][L 182] Point processed, 0 Pokemons seen!
> 	Line 477437: [2016-07-31 04:40:12,602][  worker-1][    INFO][L 155] Visiting point removed (removed)
> 	Line 477438: [2016-07-31 04:40:12,602][  worker-1][    INFO][L 211] Creating a new direct request...
> 	Line 477439: [2016-07-31 04:40:12,602][  worker-1][    INFO][L 218] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
> 	Line 477440: [2016-07-31 04:40:12,608][  worker-1][    INFO][L 179] Execution of RPC
> 	Line 477441: [2016-07-31 04:40:12,611][  worker-1][    INFO][L 788] Starting new HTTPS connection (1): pgorelease.nianticlabs.com
> 	Line 477491: [2016-07-31 04:40:12,936][  worker-1][    INFO][L 187] Cleanup of request!
> 	Line 477492: [2016-07-31 04:40:12,936][  worker-1][    INFO][L 182] Point processed, 0 Pokemons seen!
> 	Line 479155: [2016-07-31 04:40:25,216][  worker-1][    INFO][L 259] Worker (re)starting up!
> 	Line 479156: [2016-07-31 04:40:25,216][  worker-1][    INFO][L  57] pgoapi v1.1.5 - Copyright (c) 2016 tjado <https://github.com/tejado>
> 	Line 479157: [2016-07-31 04:40:25,216][  worker-1][    INFO][L  51] Login for: removed
> 	Line 479158: [2016-07-31 04:40:25,217][  worker-1][    INFO][L 788] Starting new HTTPS connection (1): sso.pokemon.com
> 	Line 479265: [2016-07-31 04:40:26,102][  worker-1][    INFO][L  96] PTC Login successful
> 	Line 479266: [2016-07-31 04:40:26,104][  worker-1][    INFO][L 115] Starting RPC login sequence (app simulation)
> 	Line 479267: [2016-07-31 04:40:26,104][  worker-1][    INFO][L 213] Creating a new request...
> 	Line 479268: [2016-07-31 04:40:26,104][  worker-1][    INFO][L 222] Adding 'GET_PLAYER' to RPC request
> 	Line 479269: [2016-07-31 04:40:26,104][  worker-1][    INFO][L 222] Adding 'GET_HATCHED_EGGS' to RPC request
> 	Line 479270: [2016-07-31 04:40:26,104][  worker-1][    INFO][L 222] Adding 'GET_INVENTORY' to RPC request
> 	Line 479271: [2016-07-31 04:40:26,104][  worker-1][    INFO][L 222] Adding 'CHECK_AWARDED_BADGES' to RPC request
> 	Line 479272: [2016-07-31 04:40:26,104][  worker-1][    INFO][L 218] Adding 'DOWNLOAD_SETTINGS' to RPC request including arguments
> 	Line 479273: [2016-07-31 04:40:26,104][  worker-1][    INFO][L 179] Execution of RPC
> 	Line 479274: [2016-07-31 04:40:26,105][  worker-1][    INFO][L 788] Starting new HTTPS connection (1): pgorelease.nianticlabs.com

**Comment by ferazambuja** [comment]
It's the new 5 second per scan limit.

**Comment by pokemonracer** [comment]
http://imgur.com/kXrznPF seems like.

**Comment by nathaned** [comment]
@pokemonracer line 188 of worker.py

**Comment by vDrag0n** [comment]
Is it just me or do they not seem to be restarting after killed?

**Comment by kravock** [comment]
@vDrag0n yeah, they're not restarting. I'm getting a lot of workers getting exceptions now also.

**Comment by modrzew** [comment]
Please check out v0.4.1. You'll probably want more workers than before.

**Comment by kravock** [comment]
How many more workers than before would you recommend? Also, is it better for the worker points to be overlapping? The circles that show in the overlay.

**Comment by modrzew** [comment]
Each worker can scan one point every 5 seconds, and single cycle should finish under 15 minutes in order not to have missed spawns. That means keeping under 180 points per cycle should be enough.

**Comment by kravock** [comment]
More or less points per cycle is better? Got ~195 currently.

**Comment by Cy4n1d3** [comment]
Less is better if you want to lower the load on each worker.

**Comment by vDrag0n** [comment]
how do you calculate the points per cycle?

**Comment by nathaned** [comment]
@vDrag0n just run worker.py and it tells you at the top

**Comment by captcho** [comment]
@pokemonracer do you solved the problem?
