### ISSUE TITLE
Best Approach to Integration?

### ISSUE THREAD

**Issue by Brideau** [modrzew/pokeminer#87]
Hey there,

I created [Pokelyzer](https://github.com/Brideau/pokelyzer), a database schema that supports doing advanced analytics on historical Pokemon Go data using GIS software (e.g. ArcGIS/QGIS) and BI tools like Tableau or PowerBI. You might have come across it in the Silph Road subreddit post: [Finding Hotpots for Locally Rare Pokemon Using Tableau](https://www.reddit.com/r/TheSilphRoad/comments/4uvwme/finding_hotpots_for_locally_rare_pokemon_using/). 

I recently built an endpoint for the PokemonGo-Map app to receive their webhook pushes: http://www.whackdata.com/2016/07/31/pokelyzer-webhook-integration-pokemongo-map/ I was wondering if you might consider adding something similar to your (if you haven't already - I didn't spot it)?

It looks like a really quick add on - maybe 15 lines of code total - and would be especially easy given yours is a fork of theirs.

If you do, keep me posted!

**Comment by ferazambuja** [comment]
That would be great. Even more now that it's almost impossible to scan a decent area with a single worker.

**Comment by plague180** [comment]
I think this would be pretty cool too.

**Comment by theresthatguy** [comment]
I agree. This could be very useful.

**Comment by modrzew** [comment]
I don't see much point in creating a webhook mechanism - database is accessible from outside, you can poll for new changes (e.g. by storing last row ID and getting only new ones). Moreover, you'd also need to be prepared that X workers would simultaneously attack your app with hundreds of requests. Database (e.g. MySQL) is prepared for that, but is your app?

I think the best approach is to create a separate external process that polls for changes in database and does whatever you want with those - for example, pushes them to your app. I don't see any need why that process should be part of pokeminer. Pokeminer's main job is to put entries in the database.

**Comment by Brideau** [comment]
Polling is an inefficient use of resources and doesn't scale well when you have more than one service requesting data - webooks were invented to solve that problem. 

For example, one person that's using Pokelyzer right now is covering 100 distinct geographic areas, and each sends data as soon as it gets it into Pokelyzer, which ingests it immediately. The alternative - to have a service that polls 100 separate services every X seconds whether there is data or not - is not nearly as clean an approach.

The Pokelyzer webhook receiver runs server-side along with the applications that collect the data, so no ports are exposed to the public at all. If you chose to run them in separate sites, you could expose it to only the necessary IP addresses of your respective servers.

The reason why people build webhooks into their application is for precisely the thing you mentioned above: so that they can focus at what their good it. Pokeminer does a great job at gather data and storing it in a database for basic analysis. Pokelyzer focuses only on the latter part alone, allowing advanced BI and GIS tools to plug into it for doing a deeper dive for people with that skill set. Building a webhook interface allows you to make your product better, while also allowing it to integrate with tools like mine with no development effort on your behalf after the initial creation of a webhook.

**Comment by ferazambuja** [comment]
If webhooks are out of the question could an external db option with extra fields be implemented?

Unfortunately pokeminer right now barely collect enough information on its on db. That's the reasons that I'm running 18 pokemaps with pokelyzer.

**Comment by modrzew** [comment]
@Brideau I see the point of integrating with app without touching the code. I still don't think that webhooks are a must-have feature - I designed pokeminer so that data is *easily* accessible from outside via database. I will add it to my todo list, but it's a low priority. Nonetheless if you want to implement said 15 lines of code, feel free to open a pull request - if it fits into the rest of pokeminer I'll be happy to merge it.

@ferazambuja what information besides EncounterID is not stored?

**Comment by ferazambuja** [comment]
Sorry, I was a bit dramatic :)  EncounterID and Time2Hidden.
Since pokeminer intent is to collect a large area and data, this two are crucial for later analysis. 
Brideau how about a pokeminer database translator uploader meanwhile? With this two extra columns, you have all the info you need?

**Comment by Brideau** [comment]
@modrzew Sounds good, I'll take a look into doing a pull request once I've cleaned up a few more things with my project.

@ferazambuja That could be useful as well, and would be a good stop-gap measure in the meantime. I'll have a look.

**Comment by modrzew** [comment]
@ferazambuja Time2Hidden and expire_timestamp are the same information in 2 formats, aren't they? So the only thing really missing is EncounterID. But I've seen someone saying that the same Pokemon spawning at the same location at different times could have the same EncounterID, so I was reluctant on building database around it.

**Comment by ferazambuja** [comment]
Brideau probably can expand a bit more on the time2hidden. PGO-mapscan-opt deals with them separate. 
I never experienced the duplicated encounterID and the only way for us to know is if this data is saved.

**Comment by Brideau** [comment]
"Time to hidden" is the number of milliseconds until the pokemon disappears, while expire timestamp is the present time plus "time to hidden".

**Comment by modrzew** [comment]
Time to hidden decreases with time, expire timestamp is constant (there may be minor fluctuations ranging a few ms because of short delay between moment when you generate current timestamp and moment when you store value in the database, but I wrote workarounds for that). My question is: why would you want to store value that decreases over time in database? Especially when it contains exactly the same information as expire_timestamp, but in different format. IMO that's just asking for a headache related to duplicated data.

**Comment by Brideau** [comment]
Yeah the approach we're taking now is to just update the past record with the newest one if a duplicate is detected, but in some cases it could be useful to have that data. If you're trying to find out if a rare Pokemon spawns for a long time, for example, you could hunt for the max value of time to hidden for a single spawn. But that's not exactly a safe default if the user isn't fully aware of how the data is stored or how to properly query it.

**Comment by Brideau** [comment]
@modrzew I just created a pull request with this addition: https://github.com/modrzew/pokeminer/pull/162

**Comment by modrzew** [comment]
Moving the discussion to #162, then.
