### ISSUE TITLE
[Feature Request] Master-Slave workers

### ISSUE THREAD

**Issue by theresthatguy** [modrzew/pokeminer#88]
The way Go-Map can run multiple scanners with one account I think would be helpful in Pokeminer since this fork is meant to run multiple scanners at a time. Say if each account could run 3 scanners, then with  20 accounts I would be able to run 60 scanners and cover a much greater area to scan and with a lot less tedious work of setting up email/PTC accounts or the pokeminer config file or keeping track of all these passwords.

**Comment by modrzew** [comment]
If I understand correctly, you want to use the same physical PTC session (as in: the same access token, the same connection etc.) to scan multiple places *at the same time*? That's just asking for a ban.

You can use the same credentials over and over in config, and I think that's *slightly* less asking for a ban.
