### ISSUE TITLE
How many workers for certain area?

### ISSUE THREAD

**Issue by pokemonracer** [modrzew/pokeminer#89]
Let's optimize. I want to keep my ability to see reliable data of live pokemons but still scan larger areas for science.

After the latest updates from Ninantic, how many workers would be best for certain radius/area of x square km? How many points should my workers visit per cycle?

**Comment by Aiyubi** [comment]
there is some stuff described in #84

**Comment by pokemonracer** [comment]
oh yeah, thanks. So..

- Less is better
- "Each worker can scan one point every 5 seconds, and single cycle should finish under 15 minutes in order not to have missed spawns. That means keeping under 180 points per cycle should be enough."

I'm running 120 workers for 100 square km area, my points per cycle value is still ~98.6.

**Comment by theresthatguy** [comment]
How are you creating so many email/PTC accounts?

**Comment by amistad18** [comment]
> How are you creating so many email/PTC accounts?

https://github.com/modrzew/pokeminer/issues/72#issuecomment-236391871
