### ISSUE TITLE
Limit Size of log file

### ISSUE THREAD

**Issue by plague180** [modrzew/pokeminer#91]
I was just wondering if there are plans to limit the file size of the log file. I don't really need several 600 megabyte log file.

**Comment by Aiyubi** [comment]
There is: "--log-level" when starting your worker.py

**Comment by modrzew** [comment]
You don't? :crying_cat_face:

Yeah, the best way right now is to use `--log-level` and set it to `WARNING` or `ERROR`.

**Comment by plague180** [comment]
I cant believe I didn't notice that when I was adding my own custom args. Thanks guys!
