### ISSUE TITLE
What dose BAD LOGIN means?

### ISSUE THREAD

**Issue by ziofat** [modrzew/pokeminer#95]
Some of my workers appear BAD LOGIN or KILLED message, and I have to restart the script to make them work again. I didn't find related logs in the log file.
I want to know why there is a BAD LOGIN, the username/password is correct and the workers sometimes can run.

**Comment by Aiyubi** [comment]
check your workers.log to see more details

also your workers should restart in the up-to-date version after some time

**Comment by modrzew** [comment]
`BAD LOGIN` is displayed after worker intercepts `NotLoggedInException` from pgoapi. Which may be raised when credentials are incorrect, but also (more likely) when potato servers are burning.

**Comment by GaelicGamer** [comment]
@ziofat or @modrzew either of you want to close this one, seems like it should be resolved.

**Comment by ziofat** [comment]
I am closing this.
