### ISSUE TITLE
Remove google maps api key from credentials.json

### ISSUE THREAD

**Issue by kravock** [modrzew/pokeminer#98]
Should the google maps api key be remove from credentials.json and put into config.py? It's something we should probably change to our own and shouldn't be in source control.

**Comment by modrzew** [comment]
It definitely should.

**Comment by GaelicGamer** [comment]
I've taken care of this in pull request #111 as well as some other changes for review.

**Comment by kravock** [comment]
Has the google maps key been moved to config.py?

**Comment by GaelicGamer** [comment]
Ahh I forgot that part, I'll add that now

**Comment by kravock** [comment]
Yeah, may as well remove the line from credentials if it will use it from config.

**Comment by GaelicGamer** [comment]
This is now part of pull request #111 correctly, on to the next one.

**Comment by modrzew** [comment]
Accidentally done while rewriting live map to Leaflet in v0.5.0.
