### ISSUE TITLE
Pokémon translations

### ISSUE THREAD

**Issue by ohh2ahh** [modrzew/pokeminer#99]
Is there an easy way to translate the Pokémon's names? It seems that the locales from PokemonGo-Map are included.

**Comment by modrzew** [comment]
Yeah, change [line 34 of `web.py`](https://github.com/modrzew/pokeminer/blob/master/web.py#L34) to point at file of your choice.

**Comment by ohh2ahh** [comment]
Thank you, it works perfectly!
